# Pandas Learning Notebook

## 1. Import Pandas

It's standard practice to import the pandas library with the alias `pd`.

In [5]:
import pandas as pd

## 2. What is a Series?

A Series is a one-dimensional labeled array capable of holding any data type (integers, strings, floats, Python objects, etc.). You can think of it as a single column of data with an associated index.

### Creating a Series

In [6]:
# Create a simple Series with default integer index
s = pd.Series([10, 20, 30, 40])
print(s)

print(pd.Series([1,2,9,0]))

0    10
1    20
2    30
3    40
dtype: int64
0    1
1    2
2    9
3    0
dtype: int64

### Custom Index

You can also define a custom index for your Series, which can be useful for labeling data points.

In [7]:
# Create a Series with a custom string index
s_custom_index = pd.Series([10,9,7.5], index=['Maths', 'English', 'MLF'])
print(s_custom_index)

Maths      10.0
English     9.0
MLF         7.5
dtype: float64

### Accessing Values

You can access values in a Series using its index.

In [8]:
# Access a value using its label
print(f"Math CGPA: {s_custom_index['Maths']}")

# Access a value using its integer position (like a list)
# nowadays pandas prefer .loc when we want by label/name and .iloc when we want by integer so it is not good to use without them
print(f"First score: {s_custom_index.iloc[0]}")

Math CGPA: 10.0
First score: 10.0

## 3. What is a DataFrame?

The DataFrame is the most important Pandas object. It's a two-dimensional, size-mutable, and potentially heterogeneous tabular data structure with labeled axes (rows and columns). Think of it like an Excel sheet, a SQL table, or a dataset.

### Creating Your First DataFrame

DataFrames are commonly created from dictionaries, where keys become column names and values are lists of data for each column.

In [9]:
# Create a DataFrame from a dictionary
data = {
    "Name": ["Aman", "Riya", "Karan"],
    "Age": [21, 22, 20],
    "Marks": [85, 90, 78]
}

df = pd.DataFrame(data)
print(df)

    Name  Age  Marks
0   Aman   21     85
1   Riya   22     90
2  Karan   20     78

### Important Terminology

*   **Rows:** Horizontal entries, identified by an index (e.g., 0, 1, 2 in the example above).
*   **Columns:** Vertical entries, identified by column names (e.g., 'Name', 'Age', 'Marks').

## 4. Basic Dataset Inspection

Inspecting your data is often the very first step in any data analysis workflow. These methods help you get a quick overview of your DataFrame's structure and content.

### `head()`

Shows the first `n` rows (default is 5). Useful for a quick peek at the data.

In [10]:
# Display the first 5 rows
print("df.head():\n", df.head())

# Display the first 2 rows
print("\ndf.head(2):\n", df.head(2))

df.head():
     Name  Age  Marks
0   Aman   21     85
1   Riya   22     90
2  Karan   20     78

df.head(2):
    Name  Age  Marks
0  Aman   21     85
1  Riya   22     90

### `tail()`

Shows the last `n` rows (default is 5). Useful for checking the end of the data, especially after sorting or appending.

In [11]:
# Display the last 5 rows
print("df.tail():\n", df.tail())

# Display the last 1 row
print("\ndf.tail(1):\n", df.tail(1))

df.tail():
     Name  Age  Marks
0   Aman   21     85
1   Riya   22     90
2  Karan   20     78

df.tail(1):
     Name  Age  Marks
2  Karan   20     78

### `shape`

Returns a tuple representing the dimensionality of the DataFrame (rows, columns). This is very important for understanding the size of your dataset.

In [12]:
# Get the number of rows and columns
print("df.shape:", df.shape)
print(f"Meaning: {df.shape[0]} rows and {df.shape[1]} columns")

df.shape: (3, 3)
Meaning: 3 rows and 3 columns

### `columns`

Returns a list of all column names in the DataFrame.

In [13]:
# Get column names
print("df.columns:", df.columns)

df.columns: Index(['Name', 'Age', 'Marks'], dtype='object')

### `info()`

This method prints a concise summary of a DataFrame, including the index dtype and column dtypes, non-null values, and memory usage. This is super important for quickly checking data types and identifying missing values.

In [14]:
# Get a summary of the DataFrame
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Name    3 non-null      object
 1   Age     3 non-null      int64
 2   Marks   3 non-null      int64
dtypes: int64(2), object(1)
memory usage: 204.0+ bytes

### `describe()`

Generates descriptive statistics that summarize the central tendency, dispersion, and shape of a dataset's distribution. By default, this only includes numerical columns.

In [15]:
# Get descriptive statistics for numerical columns
print("df.describe():\n", df.describe())

df.describe():
         Age      Marks
count   3.0   3.000000
mean   21.0  84.333333
std     1.0   6.027714
min    20.0  78.000000
25%    20.5  81.500000
50%    21.0  85.000000
75%    21.5  87.500000
max    22.0  90.000000

## 5. Selecting Columns

DataFrames allow flexible ways to select one or more columns.

### Single Column

Selecting a single column returns a Pandas Series.

In [16]:
# Select the 'Name' column
name_series = df["Name"]
print("Type of df['Name']:", type(name_series))
print(name_series)

Type of df['Name']: <class 'pandas.core.series.Series'>
0     Aman
1     Riya
2    Karan
Name: Name, dtype: object

### Multiple Columns

To select multiple columns, pass a list of column names. This will return a DataFrame.

In [17]:
# Select 'Name' and 'Marks' columns
name_marks_df = df[["Name", "Marks"]]
print("Type of df[['Name', 'Marks']]:", type(name_marks_df))
print(name_marks_df)

Type of df[['Name', 'Marks']]: <class 'pandas.core.frame.DataFrame'>
    Name  Marks
0   Aman     85
1   Riya     90
2  Karan     78

### Important Difference

*   **Single brackets `df["Column"]`**: Returns a `Series`.
*   **Double brackets `df[["Column"]]`**: Returns a `DataFrame` (even if it's just one column). This distinction is very important for subsequent operations.

## 6. Selecting Rows

Pandas provides two primary methods for selecting rows:

*   **`.loc`**: Label-based selection. Used for selecting by row and column labels.
*   **`.iloc`**: Integer-location based selection. Used for selecting by integer positions.

### `loc` → Label-based

Use `loc` to select rows by their index labels (which are 0, 1, 2 by default in our DataFrame).

In [18]:
# Select the row with index label 0
print("df.loc[0]:\n", df.loc[0])

df.loc[0]:
 Name     Aman
Age        21
Marks      85
Name: 0, dtype: object

### `iloc` → Index-position based

Use `iloc` to select rows by their integer positions (0-indexed).

In [19]:
# Select the row at integer position 0
print("df.iloc[0]:\n", df.iloc[0])

df.iloc[0]:
 Name     Aman
Age        21
Marks      85
Name: 0, dtype: object

### Selecting Specific Rows & Columns

You can combine `loc` or `iloc` to select specific rows and columns simultaneously.

In [20]:
# Select 'Name' from the row with label 0
print("df.loc[0, 'Name']:", df.loc[0, "Name"])

# Select 'Age' from the row at integer position 2
print("df.iloc[2, 1]:", df.iloc[2, 1]) # 2nd row (Karan), 1st column (Age)

df.loc[0, 'Name']: Aman
df.iloc[2, 1]: 20

### Multiple Rows

Both `loc` and `iloc` support slicing for multiple rows.

In [21]:
# Select rows with labels 0 to 1 (inclusive)
print("df.loc[0:1]:\n", df.loc[0:1])

# Select rows at integer positions 0 to 1 (exclusive of 2)
print("\ndf.iloc[0:2]:\n", df.iloc[0:2])

df.loc[0:1]:
    Name  Age  Marks
0  Aman   21     85
1  Riya   22     90

df.iloc[0:2]:
    Name  Age  Marks
0  Aman   21     85
1  Riya   22     90

### Important Difference from Python Slicing

When slicing with `loc` using `df.loc[start:end]`, **both** the `start` and `end` labels are **inclusive**. This is different from standard Python list slicing, where the `end` is exclusive.

## 7. Filtering Data (Most Important Skill)

Filtering is a fundamental operation in data science. It allows you to select a subset of your data based on one or more conditions. This is often called boolean indexing.

### Example: Single Condition

Let's filter for students who scored more than 80 marks.

In [22]:
# Filter for students with Marks > 80
students_high_marks = df[df["Marks"] > 80]         # df[] will give all then inside another df['Marks'] which will give marks and we are checking things there
print("Students with Marks > 80:\n", students_high_marks)

Students with Marks > 80:
    Name  Age  Marks
0  Aman   21     85
1  Riya   22     90

### Multiple Conditions

You can combine multiple conditions using logical operators (`&` for AND, `|` for OR, `~` for NOT). Remember to enclose each condition in parentheses.

In [23]:
# Filter for students with Marks > 80 AND Age > 20
filtered_df = df[(df['Marks'] > 80) & (df['Age'] > 20)]
print("Students with Marks > 80 and Age > 20:\n", filtered_df)

Students with Marks > 80 and Age > 20:
    Name  Age  Marks
0  Aman   21     85
1  Riya   22     90

### Real Data Science Usage

Filtering is used extensively for tasks like:

*   Identifying specific types of transactions (e.g., fraud).
*   Selecting customers based on demographics or behavior.
*   Analyzing data for specific time periods or categories.
*   Handling outliers or anomalies.

## 8. Adding New Columns

Adding new columns to a DataFrame is a very common operation, often used to derive new features or categories from existing data.

### Example: Boolean Column

Let's add a 'Passed' column based on whether 'Marks' are above 40.

In [24]:
# Add a 'Passed' column
df["Passed"] = df["Marks"] > 40
df["Good_Student"] = df["Marks"] > 80
print("DataFrame with 'Passed' column:\n", df)

DataFrame with 'Passed' column:
     Name  Age  Marks  Passed  Good_Student
0   Aman   21     85    True          True
1   Riya   22     90    True          True
2  Karan   20     78    True         False

### Mathematical Columns

You can also perform mathematical operations on existing columns to create new ones.

In [25]:
# Add a 'Bonus' column
df["Bonus"] = df["Marks"] + 5
print("\nDataFrame with 'Bonus' column:\n", df)

DataFrame with 'Bonus' column:
     Name  Age  Marks  Passed  Good_Student  Bonus
0   Aman   21     85    True          True     90
1   Riya   22     90    True          True     95
2  Karan   20     78    True         False     83

## 9. Updating Data

Modifying existing data in a DataFrame is crucial for data cleaning and transformation.

### Example: Update a Single Value

Use `.loc` to update a specific cell by its row label and column label.

In [26]:
# Update Aman's marks to 95
df.loc[0, "Marks"] = 95
df.loc[2, "Age"] = 19
print("DataFrame after updating Aman's Marks:\n", df)

DataFrame after updating Aman's Marks:
     Name  Age  Marks  Passed  Good_Student  Bonus
0   Aman   21     95    True          True     90
1   Riya   22     90    True          True     95
2  Karan   19     78    True         False     83

### Update Multiple Rows

You can combine filtering with `.loc` to update multiple rows that meet a certain condition. This is a very powerful technique.

In [27]:
# Update marks for all students with Marks < 80 to 80
df.loc[df["Marks"] < 85, "Marks"] = 60
print("\nDataFrame after updating Marks < 80 to 80:\n", df)

DataFrame after updating Marks < 80 to 80:
     Name  Age  Marks  Passed  Good_Student  Bonus
0   Aman   21     95    True          True     90
1   Riya   22     90    True          True     95
2  Karan   19     60    True         False     83

## 10. Sorting Data

Sorting allows you to reorder your DataFrame rows based on the values in one or more columns.

### Sort by One Column

By default, `sort_values` sorts in ascending order.

In [28]:
# Sort by 'Marks' in ascending order
print("Sorted by Marks (ascending):\n", df.sort_values("Marks"))

Sorted by Marks (ascending):
     Name  Age  Marks  Passed  Good_Student  Bonus
2  Karan   19     60    True         False     83
1   Riya   22     90    True          True     95
0   Aman   21     95    True          True     90

### Descending Order

Use the `ascending=False` parameter for descending order.

In [29]:
# Sort by 'Marks' in descending order
print("\nSorted by Marks (descending):\n", df.sort_values("Marks", ascending=False))

Sorted by Marks (descending):
     Name  Age  Marks  Passed  Good_Student  Bonus
0   Aman   21     95    True          True     90
1   Riya   22     90    True          True     95
2  Karan   19     60    True         False     83

### Sort by Multiple Columns

You can sort by multiple columns by passing a list of column names. You can also specify ascending/descending order for each column individually.

In [30]:
# Sort by 'Age' ascending, then by 'Marks' descending
print("\nSorted by Age (asc) then Marks (desc):\n",
      df.sort_values(
          ["Age", "Marks"],
          ascending=[True, False]
      )
     )

Sorted by Age (asc) then Marks (desc):
     Name  Age  Marks  Passed  Good_Student  Bonus
2  Karan   19     60    True         False     83
0   Aman   21     95    True          True     90
1   Riya   22     90    True          True     95

## 11. Missing Values (Critical)

Real-world datasets almost always contain missing values. Handling them properly is a critical step in data preprocessing.

### Example DataFrame with Missing Values

Missing values are often represented as `None` or `NaN` (Not a Number).

In [31]:
import numpy as np

missing_data = {
    "Name": ["Aman", "Riya", None, "Deepak"],
    "Marks": [90, np.nan, 70, 88],
    "City": ["Delhi", "Mumbai", "Pune", None]
}

df_missing = pd.DataFrame(missing_data)
print("Original DataFrame with missing values:\n", df_missing)

Original DataFrame with missing values:
      Name  Marks    City
0    Aman   90.0   Delhi
1    Riya    NaN  Mumbai
2    None   70.0    Pune
3  Deepak   88.0    None

### Detect Missing Values

The `isnull()` method returns a boolean DataFrame indicating where values are missing.

In [32]:
# Detect missing values
print("\nMissing values (boolean DataFrame):\n", df_missing.isnull())

Missing values (boolean DataFrame):
     Name  Marks   City
0  False  False  False
1  False   True  False
2   True  False  False
3  False  False   True

### Count Missing Values

Combining `isnull()` with `sum()` is a very common way to count missing values per column.

In [33]:
# Count missing values per column
print("\nCount of missing values per column:\n", df_missing.isnull().sum())

Count of missing values per column:
 Name     1
Marks    1
City     1
dtype: int64

### Drop Missing Values

The `dropna()` method removes rows or columns with missing values. By default, it drops rows that contain *any* missing values.

In [34]:
# Drop rows with any missing values
df_dropped = df_missing.dropna()
print("\nDataFrame after dropping rows with missing values:\n", df_dropped)

DataFrame after dropping rows with missing values:
    Name  Marks   City
0  Aman   90.0  Delhi

### Fill Missing Values

The `fillna()` method allows you to replace missing values with a specified value (e.g., 0, mean, median, mode, or a constant string).

In [35]:
# Fill numerical missing values with 0 and categorical missing values with 'Unknown'
df_filled = df_missing.copy()
df_filled['Marks'] = df_filled['Marks'].fillna(0) # Fill numerical column
df_filled['Name'] = df_filled['Name'].fillna('Unknown') # Fill object column
df_filled['City'] = df_filled['City'].fillna('Unknown') # Fill object column
print("\nDataFrame after filling missing values:\n", df_filled)

DataFrame after filling missing values:
       Name  Marks     City
0     Aman   90.0    Delhi
1     Riya    0.0   Mumbai
2  Unknown   70.0     Pune
3   Deepak   88.0  Unknown

### Real ML Usage

In machine learning, you never ignore missing values. Common strategies include:

*   **Removal:** Dropping rows/columns if missing data is sparse or the column is not important.
*   **Imputation:** Filling missing values using statistical methods (mean, median, mode) or more advanced techniques (e.g., regression imputation, K-Nearest Neighbors imputation).
*   **Prediction:** Treating missing values as a target variable in a separate model.

## 12. Reading CSV Files

Most real-world datasets are stored in files like CSV (Comma Separated Values) or Excel. Pandas provides powerful functions to read these files directly into DataFrames.

### Upload CSV in Colab (Optional, for local files)

If you have a CSV file locally, you can upload it to your Colab environment using the file upload button (folder icon on the left panel) or by running a small code snippet. For demonstration, we'll create a dummy CSV file.

In [36]:
# Create a dummy CSV file for demonstration
# this will create a dymmy think suppose what happen if we upload a file
data_csv = """
Name,Age,Marks,City
Aman,21,85,Delhi
Riya,22,90,Mumbai
Karan,20,78,Delhi
Simran,23,95,Pune
"""
# 2. This opens a brand new file named "sample_data.csv" in "write" mode ("w").
# It pastes the string above into that file, and then saves it. and now we can use that sample_data.csv we dont use data_csv because we transfer that string in that sampelcsv file you got that.
with open("sample_data.csv", "w") as f:
    f.write(data_csv)

# now this pd.read_csv will read this file in dataframe format
df_csv = pd.read_csv("sample_data.csv")
print("DataFrame read from sample_data.csv:\n")
print(df_csv)

DataFrame read from sample_data.csv:

     Name  Age  Marks    City
0    Aman   21     85   Delhi
1    Riya   22     90  Mumbai
2   Karan   20     78   Delhi
3  Simran   23     95    Pune

### First Thing After Reading

After loading any new dataset, always perform these initial checks to understand its structure and quality:

In [37]:
# Always do these first
# this is considered as a good practice to follow.

display(df_csv.head())         # See the first few rows
df_csv.info()                  # Check data types, non-null counts, memory
display(df_csv.describe())      # Get descriptive statistics for numerical columns
print("Missing values per column:\n", df_csv.isnull().sum()) # Count missing values

     Name  Age  Marks    City
0    Aman   21     85   Delhi
1    Riya   22     90  Mumbai
2   Karan   20     78   Delhi
3  Simran   23     95    Pune

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Name    4 non-null      object
 1   Age     4 non-null      int64
 2   Marks   4 non-null      int64
 3   City    4 non-null      object
dtypes: int64(2), object(2)
memory usage: 260.0+ bytes

             Age     Marks
count   4.000000   4.00000
mean   21.500000  87.00000
std     1.290994   7.25718
min    20.000000  78.00000
25%    20.750000  83.25000
50%    21.500000  87.50000
75%    22.250000  91.25000
max    23.000000  95.00000

Missing values per column:
 Name     0
Age      0
Marks    0
City     0
dtype: int64

### Mini Real Dataset Example Operations

Let's apply some of the learned techniques to our `df_csv` DataFrame.

In [38]:
# Find students from Delhi
delhi_students = df_csv[df_csv['City']=='Delhi']
print("Students from Delhi:\n", delhi_students)

# Students with Marks > 80
high_scoring_students = df_csv[df_csv["Marks"] > 80]
print("\nStudents with Marks > 80:\n", high_scoring_students)

# Calculate average Marks
avg_marks = df_csv["Marks"].mean()
print(f"\nAverage Marks: {avg_marks:.2f}")

# Find Highest Marks
highest_marks = df_csv["Marks"].max()
print(f"Highest Marks: {highest_marks}")

Students from Delhi:
     Name  Age  Marks   City
0   Aman   21     85  Delhi
2  Karan   20     78  Delhi

Students with Marks > 80:
      Name  Age  Marks    City
0    Aman   21     85   Delhi
1    Riya   22     90  Mumbai
3  Simran   23     95    Pune

Average Marks: 87.00
Highest Marks: 95

## What You MUST Practice Now

Before moving to more intermediate Pandas concepts, ensure you are very comfortable with these fundamental operations. They are daily skills in data science:

*   DataFrame creation
*   Selecting rows/columns (`[]`, `.loc`, `.iloc`)
*   Filtering data (boolean indexing)
*   Sorting data (`sort_values`)
*   Adding new columns
*   Handling missing values (`isnull()`, `dropna()`, `fillna()`)
*   Reading CSV files (`read_csv`)
*   Basic inspection (`head()`, `info()`, `describe()`, `isnull().sum()`)

## Beginner Assignment: Practice Tasks

**Instructions:** For each task, write and execute the Python code in the cells below. Try to do it without looking back at the examples!

### Task 1: Create a DataFrame

Create a Pandas DataFrame named `employees_df` with the following columns and 5 employee records:

*   `Name`
*   `Age`
*   `Salary`

In [39]:
# Your code for Task 1 here
# Example data to get you started (feel free to change):
employees_dictionary={
    'Name':['Alice', 'Bob', 'Charlie', 'David', 'Eve'],
    'Age':[30, 24, 35, 29, 42],
    'Salary':[60000, 45000, 75000, 55000, 90000]
}

employees_df = pd.DataFrame(employees_dictionary)
display(employees_df)

      Name  Age  Salary
0    Alice   30   60000
1      Bob   24   45000
2  Charlie   35   75000
3    David   29   55000
4      Eve   42   90000

### Task 2: Filter Employees

From `employees_df`, find and display:

*   Employees older than 25.
*   Employees with a salary greater than 50,000.

In [40]:
# Your code for Task 2 here
print("Employees older than 25 (means age > 25):\n")
employees_age_gt_25 = employees_df[employees_df['Age'] > 25]
display(employees_age_gt_25)

print("\nEmployees with salary > 50000:\n")
employees_salary_gt_50k = employees_df[employees_df['Salary'] > 50000]
display(employees_salary_gt_50k)

Employees older than 25 (means age > 25):

      Name  Age  Salary
0    Alice   30   60000
2  Charlie   35   75000
3    David   29   55000
4      Eve   42   90000

Employees with salary > 50000:

      Name  Age  Salary
0    Alice   30   60000
2  Charlie   35   75000
3    David   29   55000
4      Eve   42   90000

### Task 3: Add a New Column

Add a new column named `Bonus` to `employees_df`. The bonus should be 10% of their `Salary`.

In [41]:
# Your code for Task 3 here
employees_df['Bonus'] = employees_df['Salary'] * 0.1
display(employees_df)

      Name  Age  Salary   Bonus
0    Alice   30   60000  6000.0
1      Bob   24   45000  4500.0
2  Charlie   35   75000  7500.0
3    David   29   55000  5500.0
4      Eve   42   90000  9000.0

### Task 4: Sort Employees

Sort `employees_df` by `Salary` in descending order and display the result.

In [42]:
# Your code for Task 4 here
sorted_employees = employees_df.sort_values(by='Salary', ascending=False)
display(sorted_employees)

      Name  Age  Salary   Bonus
4      Eve   42   90000  9000.0
2  Charlie   35   75000  7500.0
0    Alice   30   60000  6000.0
3    David   29   55000  5500.0
1      Bob   24   45000  4500.0

### Task 5: Handle Missing Values

Create a new DataFrame called `employees_missing_df` by introducing some missing values (e.g., `np.nan` for numerical columns, `None` for string columns) into `employees_df`.

Then, for `employees_missing_df`:

*   Detect and count the number of missing values per column.
*   Fill the missing `Age` values with the average `Age`.
*   Fill the missing `Salary` values with 0.
*   Fill any missing `Name` values with the string 'Unknown'.

Display the DataFrame after each step (initial, counts, filled).

In [43]:
# Your code for Task 5 here

# Step1: Creating a dataframe with some missing values (e.g None, null, NaN)
import numpy as np

# i am creating a copy of employees_df then change some values to nan and none
employees_missing_df = employees_df.copy()
employees_missing_df.loc[1, 'Age'] = np.nan
employees_missing_df.loc[3, 'Salary'] = np.nan
employees_missing_df.loc[0, 'Name'] = None
display("original employees_missing_df:\n", employees_missing_df)

# Step 2: Detect and count missing values
print("\nMissing values count:\n")
print(employees_missing_df.isnull().sum())

# Step 3: Fill missing values
# we can use .fillna(value)
employees_missing_df['Age'] =  employees_missing_df['Age'].fillna(employees_missing_df['Age'].mean())
employees_missing_df['Salary'] = employees_missing_df['Salary'].fillna(0)
employees_missing_df['Name'] = employees_missing_df['Name'].fillna("Unknown")

display("\nEmployees_missing_df after filling:\n", employees_missing_df)

'original employees_missing_df:\n'

      Name   Age   Salary   Bonus
0     None  30.0  60000.0  6000.0
1      Bob   NaN  45000.0  4500.0
2  Charlie  35.0  75000.0  7500.0
3    David  29.0      NaN  5500.0
4      Eve  42.0  90000.0  9000.0

Missing values count:

Name      1
Age       1
Salary    1
Bonus     0
dtype: int64

'\nEmployees_missing_df after filling:\n'

      Name   Age   Salary   Bonus
0  Unknown  30.0  60000.0  6000.0
1      Bob  34.0  45000.0  4500.0
2  Charlie  35.0  75000.0  7500.0
3    David  29.0      0.0  5500.0
4      Eve  42.0  90000.0  9000.0

## Intermediate Pandas Roadmap

Today we’ll cover:

*   `value_counts()`
*   `unique()` & `nunique()`
*   `groupby()` (MOST IMPORTANT)
*   Aggregation
*   Sorting grouped data
*   `apply()`
*   `lambda` functions
*   String operations
*   `merge()` and joins
*   Handling dates
*   Pivot tables
*   Real mini EDA workflow

### Sample Dataset

We’ll use this throughout.

In [44]:
import pandas as pd

data = {
    "Name": ["Aman", "Riya", "Karan", "Simran", "Rahul"],
    "Department": ["IT", "HR", "IT", "Finance", "HR"],
    "Salary": [60000, 50000, 70000, 65000, 52000],
    "Age": [24, 28, 25, 30, 27],
    "City": ["Delhi", "Mumbai", "Delhi", "Pune", "Mumbai"]
}

df = pd.DataFrame(data)

print(df)

     Name Department  Salary  Age    City
0    Aman         IT   60000   24   Delhi
1    Riya         HR   50000   28  Mumbai
2   Karan         IT   70000   25   Delhi
3  Simran    Finance   65000   30    Pune
4   Rahul         HR   52000   27  Mumbai

## 1. `value_counts()`

VERY IMPORTANT.

Used constantly in EDA.

### Example
`df["Department"].value_counts()`

**Output:**

```
IT         2
HR         2
Finance    1
```

### Real Usage

Used for:

*   class distribution
*   category counts
*   fraud detection counts
*   gender distribution
*   product frequency

VERY common in ML.

### Normalize Percentages
`df["Department"].value_counts(normalize=True)`

Gives percentages.

In [45]:
print("without normalization = True\n",df['Department'].value_counts())
print('\nwhen normalize = True', df['Department'].value_counts(normalize=True))
# df["Department"].value_counts()
# df["Department"].value_counts(normalize=True)

without normalization = True
 Department
IT         2
HR         2
Finance    1
Name: count, dtype: int64

when normalize = True Department
IT         0.4
HR         0.4
Finance    0.2
Name: proportion, dtype: float64

## 2. `unique()` and `nunique()`

### `unique()`
`df["City"].unique()`

**Output:**

```
['Delhi' 'Mumbai' 'Pune']
```

### `nunique()`
`df["City"].nunique()`

**Output:**

```
3
```

### Real Usage

Useful for:

*   categorical analysis
*   feature engineering
*   checking dataset diversity

In [46]:
print('output of .unique it will all the unique values:\n',df["City"].unique())
print("this will output the count of the unique values:\n",df["City"].nunique())

output of .unique it will all the unique values:
 ['Delhi' 'Mumbai' 'Pune']
this will output the count of the unique values:
 3

## 3. `groupby()` — MOST IMPORTANT PANDAS CONCEPT

This is HUGE.

If you master `groupby`, you become dangerous in data analysis.

### Basic Syntax
`df.groupby("Department")`

Groups rows by department.

But you need aggregation to see results.

### Average Salary by Department
`df.groupby("Department")["Salary"].mean()`

**Output:**

```
Department
Finance    65000
HR         51000
IT         65000
```

### Why `groupby` is Important

This is how companies analyze:

*   sales per city
*   revenue per category
*   average salary per department
*   average marks per class
*   customers per region

EVERYTHING.

### Multiple Aggregations
`df.groupby("Department")["Salary"].agg([
    "mean", "max", "min", "count"])
`

**Output:**

```
             mean    max    min  count
Department
Finance   65000  65000  65000      1
HR        51000  52000  50000      2
IT        65000  70000  60000      2
```

VERY IMPORTANT.

### Group By Multiple Columns
`df.groupby(["Department", "City"])["Salary"].mean()`

### Reset Index

IMPORTANT.

Groupby often creates hierarchical index.

`result = df.groupby("Department")["Salary"].mean()`

`print(result.reset_index())`

In [47]:
# if we want to only group by with some only thing like mean, average we will use it like below:
print("It will create all unique departments and their mean:\n",df.groupby("Department")['Salary'].mean())

# we can also aggreagate many things at once this is what professionals use
print("many agg values:\n", df.groupby("Department")['Salary'].agg(["mean", "max", "min", "count", "sum"]))

# we can also group by with more than two headers like department and more if we want e.g:
print("more than one column:\n")
print(df.groupby(["Department", "City"])["Salary"].mean())

# with this reset_index we can have index also to perform loc and iloc on it
result = df.groupby("Department")["Salary"].mean()
print(result.reset_index())

It will create all unique departments and their mean:
 Department
Finance    65000.0
HR         51000.0
IT         65000.0
Name: Salary, dtype: float64
many agg values:
                mean    max    min  count     sum
Department
Finance     65000.0  65000  65000      1   65000
HR          51000.0  52000  50000      2  102000
IT          65000.0  70000  60000      2  130000
more than one column:

Department  City
Finance     Pune      65000.0
HR          Mumbai    51000.0
IT          Delhi     65000.0
Name: Salary, dtype: float64
  Department   Salary
0    Finance  65000.0
1         HR  51000.0
2         IT  65000.0

## 4. Sorting Grouped Results

### Example
`result = df.groupby("Department")["Salary"].mean()`

`result.sort_values(ascending=False)`

### Real Usage

Top:

*   cities
*   products
*   departments
*   customers

Very common.

In [48]:
result = df.groupby("Department")["Salary"].mean()
result.sort_values(ascending=False)

Department
Finance    65000.0
IT         65000.0
HR         51000.0
Name: Salary, dtype: float64

## 5. `apply()` Function

SUPER IMPORTANT intermediate concept.

Used for custom operations.

### Example
`df["Salary"].apply(lambda x: x * 1.1)`

Adds 10%.

### Store Result
`df["UpdatedSalary"] = df["Salary"].apply(
    lambda x: x * 1.1
)`

### Why `apply()` Matters

Used for:

*   feature engineering
*   custom transformations
*   preprocessing

VERY common in ML pipelines.

In [59]:

df["Salary"].apply(lambda x: x * 1.1)
df["UpdatedSalary"] = df["Salary"].apply(
    lambda x: x * 1.1
)

## 6. Lambda Functions

Mini anonymous functions.

### Example
`lambda x: x * 2`

Equivalent to:

```python
def double(x):
    return x * 2
```

### Another Example
`df["AgeGroup"] = df["Age"].apply(
    lambda x: "Young" if x < 27 else "Adult"
)`

**Output:**

`Young / Adult` labels

VERY common in feature engineering.

In [57]:
# Example 1
double_lambda = lambda x: x * 2
print(double_lambda(5))

# Example 2
df["AgeGroup"] = df["Age"].apply(
    lambda x: "Young" if x < 27 else "Adult"
)
print(df)

10
     Name Department  Salary  Age    City  UpdatedSalary AgeGroup
0    Aman         IT   60000   24   Delhi        66000.0    Young
1    Riya         HR   50000   28  Mumbai        55000.0    Adult
2   Karan         IT   70000   25   Delhi        77000.0    Young
3  Simran    Finance   65000   30    Pune        71500.0    Adult
4   Rahul         HR   52000   27  Mumbai        57200.0    Adult

## 7. String Operations

Real datasets contain LOTS of text.

Pandas string methods are VERY important.

### Convert to Uppercase
`df["Name"].str.upper()`

### Lowercase
`df["City"].str.lower()`

### Contains
`df[df["City"].str.contains("Delhi")]`

### Replace Text
`df["City"].str.replace("Delhi", "New Delhi")`

### Length
`df["Name"].str.len()`

### Why Important?

Real-world datasets:

*   messy text
*   inconsistent capitalization
*   typos
*   formatting issues

String cleaning is HUGE in DS.

In [68]:
print(df['Name'].str.upper(),"\n")
print(df['City'].str.lower(),'\n')
print(df[df["City"].str.contains("Delhi")],'\n')
print(df["City"].str.replace("Delhi", "New Delhi"),'\n')
print(df["Name"].str.len())

0      AMAN
1      RIYA
2     KARAN
3    SIMRAN
4     RAHUL
Name: Name, dtype: object

0     delhi
1    mumbai
2     delhi
3      pune
4    mumbai
Name: City, dtype: object

    Name Department  Salary  Age   City  UpdatedSalary AgeGroup
0   Aman         IT   60000   24  Delhi        66000.0    Young
2  Karan         IT   70000   25  Delhi        77000.0    Young

0    New Delhi
1       Mumbai
2    New Delhi
3         Pune
4       Mumbai
Name: City, dtype: object

0    4
1    4
2    5
3    6
4    5
Name: Name, dtype: int64

## 8. `merge()` — VERY IMPORTANT

Equivalent to SQL JOIN.

Used constantly.

### Dataset 1
```python
employees = pd.DataFrame({
    "ID": [1,2,3],
    "Name": ["Aman", "Riya", "Karan"]
})
```
### Dataset 2
```python
salaries = pd.DataFrame({
    "ID": [1,2,3],
    "Salary": [60000, 50000, 70000]
})
```
### Merge
`pd.merge(employees, salaries, on="ID")`

**Output:**

```
   ID   Name  Salary
0   1   Aman   60000
1   2   Riya   50000
2   3  Karan   70000
```

### Why Important?

Real data comes from:

*   multiple CSV files
*   multiple databases
*   APIs
*   tables

You combine datasets using merges.

### Types of Joins

*   **Inner Join** (default)
    `pd.merge(a, b, on="ID", how="inner")`
*   **Left Join**
    `pd.merge(a, b, on="ID", how="left")`
*   **Right Join**
    `pd.merge(a, b, on="ID", how="right")`
*   **Outer Join**
    `pd.merge(a, b, on="ID", how="outer")`

VERY IMPORTANT for interviews too.

In [73]:
employees = pd.DataFrame({
    "ID": [1,2,3],
    "Name": ["Aman", "Riya", "Karan"]
})
salaries = pd.DataFrame({
    "ID": [1,2,3],
    "Salary": [60000, 50000, 70000]
})
pd.merge(employees, salaries, on="ID")

# Example of a left join with a missing ID in 'salaries'
salaries_missing = pd.DataFrame({
    "ID": [1, 3],
    "Salary": [60000, 70000]
})
pd.merge(employees, salaries_missing, on="ID", how="outer")

   ID   Name   Salary
0   1   Aman  60000.0
1   2   Riya      NaN
2   3  Karan  70000.0

## 9. Working with Dates

SUPER IMPORTANT in industry datasets.

### Convert to Datetime
`df["Date"] = pd.to_datetime(df["Date"])`

### Extract Year
`df["Date"].dt.year`

### Extract Month
`df["Date"].dt.month`

### Extract Day
`df["Date"].dt.day`

### Why Important?

Used in:

*   sales analysis
*   time-series
*   trends
*   forecasting

In [74]:
# Create a sample DataFrame with a date column
date_data = {
    "Event": ["Meeting", "Presentation", "Workshop"],
    "Date": ["2023-01-15", "2023-02-20", "2023-03-10"]
}
df_dates = pd.DataFrame(date_data)
display(df_dates)

# Convert to datetime
df_dates["Date"] = pd.to_datetime(df_dates["Date"])

# Extract components
df_dates["Year"] = df_dates["Date"].dt.year
df_dates["Month"] = df_dates["Date"].dt.month
df_dates["Day"] = df_dates["Date"].dt.day
print(df_dates)

          Event        Date
0       Meeting  2023-01-15
1  Presentation  2023-02-20
2      Workshop  2023-03-10

          Event       Date  Year  Month  Day
0       Meeting 2023-01-15  2023      1   15
1  Presentation 2023-02-20  2023      2   20
2      Workshop 2023-03-10  2023      3   10

## 10. Pivot Tables

VERY POWERFUL.

### Example
```python
pd.pivot_table(
    df,
    values="Salary",
    index="Department",
    aggfunc="mean"
)
```

Similar to Excel pivot tables.

### Multiple Aggregations
```python
pd.pivot_table(
    df,
    values="Salary",
    index="Department",
    aggfunc=["mean", "max"]
)
```
### Why Important?

Used for:

*   dashboards
*   summaries
*   analytics reports

In [75]:
# Example 1
print(pd.pivot_table(
    df,
    values="Salary",
    index="Department",
    aggfunc="mean"
))

# Example 2
print(pd.pivot_table(
    df,
    values="Salary",
    index="Department",
    aggfunc=["mean", "max"]
))

             Salary
Department
Finance     65000.0
HR          51000.0
IT          65000.0
               mean    max
             Salary Salary
Department
Finance     65000.0  65000
HR          51000.0  52000
IT          65000.0  70000

## 11. Real Mini EDA Workflow

This is VERY close to real Data Science work.

### Typical Workflow
```python
import pandas as pd

# df = pd.read_csv("data.csv") # Assuming 'data.csv' exists

# # basic inspection
# print(df.head())

# print(df.info())

# print(df.describe())

# # missing values
# print(df.isnull().sum())

# # category counts
# print(df["Department"].value_counts())

# # filtering
# high_salary = df[df["Salary"] > 50000]
# print(high_salary)

# # grouping
# print(df.groupby("Department")["Salary"].mean())

# # sorting
# print(df.sort_values("Salary", ascending=False))
```

This is REAL workflow.

## MOST IMPORTANT THINGS TO MASTER NOW

Spend serious time on:

*    filtering
*    `groupby`
*    aggregation
*    `apply`
*    `lambda`
*    string operations
*    `merge`
*    missing values

These are CORE data analysis skills.

## Intermediate Assignment

### Task 1

Create an employee dataset with:

*   `Name`
*   `Department`
*   `Salary`
*   `City`

### Task 2

Find:

*   average salary per department
*   max salary per city
*   employee count per department

using `groupby`.

### Task 3

Create:

`Bonus = Salary * 0.2`

using `apply()` and `lambda`.

### Task 4

Convert all city names to uppercase.

### Task 5

Create two DataFrames and merge them.

### Task 6

Create a Date column and extract:

*   year
*   month
*   day

In [97]:
from numpy._core.defchararray import capitalize
# Task-1
import pandas as pd
emp_data = {
    'name':  ['Shourya', 'Kalpana', 'Sumit', 'Dabral', 'Akash', 'Rohit'],
    'city':  ['Delhi', 'Muradabad', 'Delhi', 'Patna', 'Gaya', 'Mumbai'],
    'salary': [45000, 55000, 23000, 34000, 89000, 67000],
    'department': ['Finance', 'IT', 'IT', 'Medical', 'IT', 'Finance']
}

emp_df = pd.DataFrame(emp_data)
display(emp_df)

# Task-2
print(f"department group by mean:\n{emp_df.groupby('department')['salary'].mean()}\n")
print(f"department group by employee count per department:\n{emp_df.groupby('department')['name'].count()}\n")
print(f"max salary per city:\n{emp_df.groupby('city')['salary'].max()}\n")

# Task-3
emp_df['bonus'] = emp_df['salary'].apply(lambda x: x*1.1)
print(emp_df)

# Task-4
upper_city = emp_df['city'].str.upper()
print('\n',upper_city)

# Task-5
first_data = {
    'id':[1,2,3,4],
    'name': ['pankaj', 'jalaj','neeraj','kamal']
}

second_data = {
    'id':[1,2,3,4],
    'salary':[5000,5600,6700,4500]
}

first_df = pd.DataFrame(first_data)
second_df = pd.DataFrame(second_data)

merged_df = pd.merge(first_df,second_df, on='id')
print('\n', merged_df)

# task-6
merged_df['date'] = ['2025-05-21', '2021-09-21', '2022-02-12', '2026-03-17']
merged_df['date'] = pd.to_datetime(merged_df['date'])
merged_df['day'] = merged_df['date'].dt.day
merged_df['month'] = merged_df['date'].dt.month
merged_df['year'] = merged_df['date'].dt.year
merged_df

      name       city  salary department
0  Shourya      Delhi   45000    Finance
1  Kalpana  Muradabad   55000         IT
2    Sumit      Delhi   23000         IT
3   Dabral      Patna   34000    Medical
4    Akash       Gaya   89000         IT
5    Rohit     Mumbai   67000    Finance

department group by mean:
department
Finance    56000.000000
IT         55666.666667
Medical    34000.000000
Name: salary, dtype: float64

department group by employee count per department:
department
Finance    2
IT         3
Medical    1
Name: name, dtype: int64

max salary per city:
city
Delhi        45000
Gaya         89000
Mumbai       67000
Muradabad    55000
Patna        34000
Name: salary, dtype: int64

      name       city  salary department    bonus
0  Shourya      Delhi   45000    Finance  49500.0
1  Kalpana  Muradabad   55000         IT  60500.0
2    Sumit      Delhi   23000         IT  25300.0
3   Dabral      Patna   34000    Medical  37400.0
4    Akash       Gaya   89000         IT  97900.0
5    Rohit     Mumbai   67000    Finance  73700.0

 0        DELHI
1    MURADABAD
2        DELHI
3        PATNA
4         GAYA
5       MUMBAI
Name: city, dtype: object

    id    name  salary
0   1  pankaj    5000
1   2   jalaj    5600
2   3  neeraj    6700
3   4   kamal    4500

   id    name  salary       date  day  month  year
0   1  pankaj    5000 2025-05-21   21      5  2025
1   2   jalaj    5600 2021-09-21   21      9  2021
2   3  neeraj    6700 2022-02-12   12      2  2022
3   4   kamal    4500 2026-03-17   17      3  2026