# Data Imputation Demo

First, let's create a sample DataFrame with some missing values in both numerical and categorical columns.

In [1]:
import pandas as pd
import numpy as np

# Create a sample DataFrame with missing values
data = {
    'Numerical_Col_A': [10, 20, np.nan, 40, 50, 60, np.nan, 80, 90, 100],
    'Numerical_Col_B': [1, np.nan, 3, 4, 5, np.nan, 7, 8, 9, 10],
    'Categorical_Col_C': ['A', 'B', 'A', np.nan, 'C', 'B', 'A', 'C', np.nan, 'A'],
    'Categorical_Col_D': ['X', 'Y', 'Z', 'X', np.nan, 'Y', 'Z', 'X', 'Y', np.nan]
}
df = pd.DataFrame(data)

print("Original DataFrame with missing values:")
display(df)

Original DataFrame with missing values:

   Numerical_Col_A  Numerical_Col_B Categorical_Col_C Categorical_Col_D
0             10.0              1.0                 A                 X
1             20.0              NaN                 B                 Y
2              NaN              3.0                 A                 Z
3             40.0              4.0               NaN                 X
4             50.0              5.0                 C               NaN
5             60.0              NaN                 B                 Y
6              NaN              7.0                 A                 Z
7             80.0              8.0                 C                 X
8             90.0              9.0               NaN                 Y
9            100.0             10.0                 A               NaN

Now, let's identify numerical and categorical columns to apply the correct imputation strategy.

In [2]:
# Identify numerical and categorical columns
numerical_cols = df.select_dtypes(include=np.number).columns
categorical_cols = df.select_dtypes(exclude=np.number).columns

print("Numerical Columns:", numerical_cols.tolist())
print("Categorical Columns:", categorical_cols.tolist())

Numerical Columns: ['Numerical_Col_A', 'Numerical_Col_B']
Categorical Columns: ['Categorical_Col_C', 'Categorical_Col_D']

### Mean Imputation for Numerical Columns

We will fill missing values in numerical columns with their respective means. This is suitable for normally distributed data without significant outliers.

In [3]:
df_mean_imputed = df.copy()
for col in numerical_cols:
    if df_mean_imputed[col].isnull().any():
        mean_value = df_mean_imputed[col].mean()
        df_mean_imputed[col].fillna(mean_value, inplace=True)
        print(f"Missing values in '{col}' filled with mean: {mean_value:.2f}")

print("\nDataFrame after Mean Imputation for numerical columns:")
display(df_mean_imputed)

Missing values in 'Numerical_Col_A' filled with mean: 56.25
Missing values in 'Numerical_Col_B' filled with mean: 5.88

DataFrame after Mean Imputation for numerical columns:

/tmp/ipykernel_13744/3692255597.py:5: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df_mean_imputed[col].fillna(mean_value, inplace=True)

   Numerical_Col_A  Numerical_Col_B Categorical_Col_C Categorical_Col_D
0            10.00            1.000                 A                 X
1            20.00            5.875                 B                 Y
2            56.25            3.000                 A                 Z
3            40.00            4.000               NaN                 X
4            50.00            5.000                 C               NaN
5            60.00            5.875                 B                 Y
6            56.25            7.000                 A                 Z
7            80.00            8.000                 C                 X
8            90.00            9.000               NaN                 Y
9           100.00           10.000                 A               NaN

### Median Imputation for Numerical Columns

Alternatively, we can fill missing values in numerical columns with their medians. This is often preferred when data has outliers or is skewed, as the median is more robust to extreme values.

In [4]:
df_median_imputed = df.copy()
for col in numerical_cols:
    if df_median_imputed[col].isnull().any():
        median_value = df_median_imputed[col].median()
        df_median_imputed[col].fillna(median_value, inplace=True)
        print(f"Missing values in '{col}' filled with median: {median_value:.2f}")

print("\nDataFrame after Median Imputation for numerical columns:")
display(df_median_imputed)

Missing values in 'Numerical_Col_A' filled with median: 55.00
Missing values in 'Numerical_Col_B' filled with median: 6.00

DataFrame after Median Imputation for numerical columns:

/tmp/ipykernel_13744/703929340.py:5: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df_median_imputed[col].fillna(median_value, inplace=True)

   Numerical_Col_A  Numerical_Col_B Categorical_Col_C Categorical_Col_D
0             10.0              1.0                 A                 X
1             20.0              6.0                 B                 Y
2             55.0              3.0                 A                 Z
3             40.0              4.0               NaN                 X
4             50.0              5.0                 C               NaN
5             60.0              6.0                 B                 Y
6             55.0              7.0                 A                 Z
7             80.0              8.0                 C                 X
8             90.0              9.0               NaN                 Y
9            100.0             10.0                 A               NaN

### Mode Imputation for Categorical Columns

For categorical columns, we will fill missing values with the mode (most frequent value).

In [5]:
df_mode_imputed = df.copy()
for col in categorical_cols:
    if df_mode_imputed[col].isnull().any():
        mode_value = df_mode_imputed[col].mode()[0] # .mode() returns a Series, take the first if multiple modes
        df_mode_imputed[col].fillna(mode_value, inplace=True)
        print(f"Missing values in '{col}' filled with mode: {mode_value}")

print("\nDataFrame after Mode Imputation for categorical columns:")
display(df_mode_imputed)

Missing values in 'Categorical_Col_C' filled with mode: A
Missing values in 'Categorical_Col_D' filled with mode: X

DataFrame after Mode Imputation for categorical columns:

/tmp/ipykernel_13744/3891104835.py:5: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df_mode_imputed[col].fillna(mode_value, inplace=True)

   Numerical_Col_A  Numerical_Col_B Categorical_Col_C Categorical_Col_D
0             10.0              1.0                 A                 X
1             20.0              NaN                 B                 Y
2              NaN              3.0                 A                 Z
3             40.0              4.0                 A                 X
4             50.0              5.0                 C                 X
5             60.0              NaN                 B                 Y
6              NaN              7.0                 A                 Z
7             80.0              8.0                 C                 X
8             90.0              9.0                 A                 Y
9            100.0             10.0                 A                 X

### Combined Imputation Example

Let's apply both median imputation for numerical columns and mode imputation for categorical columns to a fresh copy of the original DataFrame.

In [6]:
df_combined_imputed = df.copy()

# Impute numerical columns with median
for col in numerical_cols:
    if df_combined_imputed[col].isnull().any():
        median_value = df_combined_imputed[col].median()
        df_combined_imputed[col].fillna(median_value, inplace=True)
        print(f"Numerical column '{col}' imputed with median: {median_value:.2f}")

# Impute categorical columns with mode
for col in categorical_cols:
    if df_combined_imputed[col].isnull().any():
        mode_value = df_combined_imputed[col].mode()[0]
        df_combined_imputed[col].fillna(mode_value, inplace=True)
        print(f"Categorical column '{col}' imputed with mode: {mode_value}")

print("\nDataFrame after Combined Imputation (Median for numerical, Mode for categorical):")
display(df_combined_imputed)

print("\nCheck for any remaining missing values:")
print(df_combined_imputed.isnull().sum())

Numerical column 'Numerical_Col_A' imputed with median: 55.00
Numerical column 'Numerical_Col_B' imputed with median: 6.00
Categorical column 'Categorical_Col_C' imputed with mode: A
Categorical column 'Categorical_Col_D' imputed with mode: X

DataFrame after Combined Imputation (Median for numerical, Mode for categorical):

/tmp/ipykernel_13744/2585867648.py:7: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df_combined_imputed[col].fillna(median_value, inplace=True)
/tmp/ipykernel_13744/2585867648.py:14: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df_combined_imputed[col].fillna(mode_value, inplace=True)

   Numerical_Col_A  Numerical_Col_B Categorical_Col_C Categorical_Col_D
0             10.0              1.0                 A                 X
1             20.0              6.0                 B                 Y
2             55.0              3.0                 A                 Z
3             40.0              4.0                 A                 X
4             50.0              5.0                 C                 X
5             60.0              6.0                 B                 Y
6             55.0              7.0                 A                 Z
7             80.0              8.0                 C                 X
8             90.0              9.0                 A                 Y
9            100.0             10.0                 A                 X

Check for any remaining missing values:
Numerical_Col_A      0
Numerical_Col_B      0
Categorical_Col_C    0
Categorical_Col_D    0
dtype: int64