# Working with CSV Files in Pandas

This notebook provides a detailed guide on how to effectively work with CSV (Comma Separated Values) files using the powerful pandas library in Python. We'll cover everything from basic loading to handling common issues and leveraging advanced parameters.

In [1]:
# First, let's create some dummy CSV files for demonstration purposes
# This helps ensure the examples are reproducible without external files.

import pandas as pd
import numpy as np
import os

# Dummy file 1: aug_train.csv for basic reading
data_basic = {
    'enrollee_id': [1, 2, 3, 4, 5],
    'city': ['Mumbai', 'Bangalore', 'Delhi', 'Kolkata', 'Chennai'],
    'gender': ['Male', 'Female', 'Male', 'Female', 'Male'],
    'relevent_experience': ['Has relevent experience', 'No relevent experience', 'Has relevent experience', 'Has relevent experience', 'No relevent experience'],
    'education_level': ['Graduate', 'Masters', 'Graduate', 'Phd', 'Graduate'],
    'experience': [2, 5, 8, 1, 10],
    'target': [0, 1, 0, 1, 0]
}
df_basic = pd.DataFrame(data_basic)
df_basic.to_csv('aug_train.csv', index=False)
print('Created aug_train.csv')

# Dummy file 2: data.tsv for `sep` parameter
data_tsv = {
    'col1': [10, 20, 30],
    'col2': ['A', 'B', 'C'],
    'col3': [1.1, 2.2, 3.3]
}
df_tsv = pd.DataFrame(data_tsv)
df_tsv.to_csv('data.tsv', index=False, sep='\t')
print('Created data.tsv')

# Dummy file 3: data_no_header.csv for `header` parameter
data_no_header = [
    [1, 'Apple', 100],
    [2, 'Banana', 150],
    [3, 'Orange', 200]
]
with open('data_no_header.csv', 'w') as f:
    for row in data_no_header:
        f.write(','.join(map(str, row)) + '\n')
print('Created data_no_header.csv')

# Dummy file 4: data_skip_rows.csv for `skiprows` parameter
data_skip_rows = [
    '# This is a comment',
    '# Another comment line',
    'ID,Product,Price',
    '1,Desk,50',
    '2,Chair,30'
]
with open('data_skip_rows.csv', 'w') as f:
    for line in data_skip_rows:
        f.write(line + '\n')
print('Created data_skip_rows.csv')

# Dummy file 5: data_dates.csv for `parse_dates` and `na_values`
data_dates = {
    'OrderDate': ['2023-01-01', '2023-01-02', '2023-01-XX', '2023-01-04'],
    'Amount': [100, 150, 200, np.nan]
}
df_dates = pd.DataFrame(data_dates)
df_dates.to_csv('data_dates.csv', index=False)
print('Created data_dates.csv')

# Dummy file 6: data_latin1.csv for `encoding`
data_latin1_content = 'Name,Description\nJosé,Camión\nMaria,Avión'
with open('data_latin1.csv', 'w', encoding='latin-1') as f:
    f.write(data_latin1_content)
print('Created data_latin1.csv')


print('\nAll dummy CSVs created successfully!')

Created aug_train.csv
Created data.tsv
Created data_no_header.csv
Created data_skip_rows.csv
Created data_dates.csv
Created data_latin1.csv

All dummy CSVs created successfully!

---

## Section 1: Introduction to CSV Files

### Theory: What are CSVs and Why Pandas?

*   **CSV (Comma Separated Values)** files are plain text files that use commas to separate values. Each line in the file represents a row of data, and within each row, commas separate the individual data fields (columns).
*   **Why datasets use CSV**: They are widely used for data exchange because of their simplicity and human-readability. Almost any spreadsheet program, database, or data analysis tool can import and export data in CSV format.
*   **Why Pandas is used**: The `pandas` library in Python provides highly optimized and flexible data structures, particularly the `DataFrame`, which is perfect for handling tabular data like that found in CSV files. `pandas` simplifies the process of reading, writing, and manipulating CSV data with powerful functions like `pd.read_csv()`.

---

## Section 2: Basic CSV Reading

### Theory

`pd.read_csv()` is the primary function in pandas used to load CSV files into a DataFrame. This is the most common and fundamental way to import datasets into your data science workflow, whether the file is stored locally or accessed via a URL.

### Syntax

```python
pd.read_csv("file_path_or_url")
```

The most basic usage involves passing the path to your CSV file (or its URL) as a string argument.

### Example: Reading a Local CSV File

In [2]:
import pandas as pd

# Read the 'aug_train.csv' file that we created earlier
df_local = pd.read_csv("aug_train.csv")

# Display the first few rows of the DataFrame
print("DataFrame loaded from 'aug_train.csv':")
display(df_local.head())

DataFrame loaded from 'aug_train.csv':

,enrollee_id,city,gender,relevent_experience,education_level,experience,target
0,1,Mumbai,Male,Has relevent experience,Graduate,2,0
1,2,Bangalore,Female,No relevent experience,Masters,5,1
2,3,Delhi,Male,Has relevent experience,Graduate,8,0
3,4,Kolkata,Female,Has relevent experience,Phd,1,1
4,5,Chennai,Male,No relevent experience,Graduate,10,0

### Output Understanding

*   The `pd.read_csv("aug_train.csv")` command reads the data from the specified file and constructs a `DataFrame` object.
*   `df_local.head()` then prints the first 5 rows of this DataFrame. This allows you to quickly inspect the data, check column names, and see if the data was loaded correctly.
*   Notice that `pandas` automatically inferred the column names from the first row of the CSV and assigned appropriate data types to each column.

### Mini Practice: Basic Local CSV Operations

Now it's your turn to try! Use the `aug_train.csv` file we just created:

1.  **Load another CSV**: Although we only created `aug_train.csv` for now, imagine you have another local CSV. The syntax would be identical. For this practice, let's just re-load `aug_train.csv` into a new DataFrame called `df_practice`.
2.  **Print first 10 rows**: Display the first 10 rows of `df_practice`.
3.  **Print shape**: Find out the number of rows and columns in `df_practice`.
4.  **Print columns**: List all the column names present in `df_practice`.

In [3]:
# Practice Task 1: Re-load aug_train.csv into df_practice
df_practice = pd.read_csv("aug_train.csv")
print("DataFrame 'df_practice' loaded successfully.")

# Practice Task 2: Print first 10 rows
print("\nFirst 10 rows of df_practice:")
display(df_practice.head(10))

# Practice Task 3: Print shape
print(f"\nShape of df_practice (rows, columns): {df_practice.shape}")

# Practice Task 4: Print columns
print("\nColumn names in df_practice:")
print(df_practice.columns.tolist())

DataFrame 'df_practice' loaded successfully.

First 10 rows of df_practice:

,enrollee_id,city,gender,relevent_experience,education_level,experience,target
0,1,Mumbai,Male,Has relevent experience,Graduate,2,0
1,2,Bangalore,Female,No relevent experience,Masters,5,1
2,3,Delhi,Male,Has relevent experience,Graduate,8,0
3,4,Kolkata,Female,Has relevent experience,Phd,1,1
4,5,Chennai,Male,No relevent experience,Graduate,10,0

Shape of df_practice (rows, columns): (5, 7)

Column names in df_practice:
['enrollee_id', 'city', 'gender', 'relevent_experience', 'education_level', 'experience', 'target']

---

## Section 3: Reading CSV from URL

### Theory

Datasets are often hosted online and can be loaded directly into pandas DataFrames from their URLs. This eliminates the need to download the file locally first, streamlining your data workflow, especially with public datasets.

### Syntax

```python
pd.read_csv("url_to_csv_file")
```

The `pd.read_csv()` function is versatile enough to accept a URL string directly, treating it just like a local file path.

### Example: Reading a CSV from an Online Source

Let's load a sample dataset from GitHub. We'll use the 'heart.csv' dataset as an example.

In [7]:
import pandas as pd

# Updated URL for a sample diabetes dataset on GitHub
url = "https://raw.githubusercontent.com/plotly/datasets/master/diabetes.csv"

# Read the CSV from the URL
df_url = pd.read_csv(url)

print(f"DataFrame loaded from URL: {url}")
display(df_url.head())

DataFrame loaded from URL: https://raw.githubusercontent.com/plotly/datasets/master/diabetes.csv

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
0,6,148,72,35,0,33.6,0.627,50,1
1,1,85,66,29,0,26.6,0.351,31,0
2,8,183,64,0,0,23.3,0.672,32,1
3,1,89,66,23,94,28.1,0.167,21,0
4,0,137,40,35,168,43.1,2.288,33,1

### Output Understanding

*   Similar to local files, `pd.read_csv()` fetches the content from the provided URL.
*   The data is then parsed and loaded into `df_url`.
*   `df_url.head()` confirms that the data, including column names and initial rows, has been correctly imported from the web.

### Mini Practice: Loading Datasets from GitHub URLs

Now, practice loading two other classic datasets directly from their GitHub raw URLs:

1.  **Titanic Dataset**: Load the Titanic dataset (often found as `titanic_train.csv` or similar) from a raw GitHub URL. Print its first 5 rows and its shape.
2.  **Iris Dataset**: Load the Iris dataset (often found as `iris.csv`) from a raw GitHub URL. Print its first 5 rows and its columns.

In [5]:
# Practice Task 1: Load Titanic dataset
titanic_url = "https://raw.githubusercontent.com/datasciencedojo/datasets/master/titanic.csv"
df_titanic = pd.read_csv(titanic_url)
print(f"\nTitanic DataFrame loaded from URL: {titanic_url}")
display(df_titanic.head())
print(f"Shape of Titanic DataFrame: {df_titanic.shape}")

# Practice Task 2: Load Iris dataset
iris_url = "https://raw.githubusercontent.com/mwaskom/seaborn-data/master/iris.csv"
df_iris = pd.read_csv(iris_url)
print(f"\nIris DataFrame loaded from URL: {iris_url}")
display(df_iris.head())
print("Columns in Iris DataFrame:")
print(df_iris.columns.tolist())

Titanic DataFrame loaded from URL: https://raw.githubusercontent.com/datasciencedojo/datasets/master/titanic.csv

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

Shape of Titanic DataFrame: (891, 12)

Iris DataFrame loaded from URL: https://raw.githubusercontent.com/mwaskom/seaborn-data/master/iris.csv

   sepal_length  sepal_width  petal_length  petal_width species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa

Columns in Iris DataFrame:
['sepal_length', 'sepal_width', 'petal_length', 'petal_width', 'species']

---

## Section 4: Important `pd.read_csv()` Parameters

Understanding `pd.read_csv()` parameters is crucial for handling diverse CSV file formats and optimizing data loading. Instead of memorizing them, focus on the 'problem solved' by each parameter.

### Parameter: `sep`

#### Theory

*   **What it does**: The `sep` parameter specifies the delimiter (separator) used in the file to separate values. By default, `pd.read_csv()` assumes a comma (`,`) as the separator.
*   **Why it is used**: Many tabular data files are not strictly comma-separated. They might use tabs (`\t`), semicolons (`;`), pipes (`|`), or other characters to delimit fields. When the default comma delimiter fails, `sep` allows you to specify the correct one.
*   **Common Mistakes**: Not specifying `sep` when the file uses a non-comma delimiter. This often results in a DataFrame with a single column containing all the data merged into one string per row.

#### Syntax

```python
pd.read_csv("file.csv", sep="delimiter_character")
```

Common values for `delimiter_character` include `','` (default), `'\t'` for tab-separated values (TSV), `';'`, or `'|'`.

#### Example: Reading a Tab-Separated File

In [8]:
import pandas as pd

# Try to read 'data.tsv' without specifying the separator (will likely fail to parse correctly)
print("Attempting to read data.tsv without 'sep':")
df_wrong_sep = pd.read_csv("data.tsv")
display(df_wrong_sep.head())

# Now, read 'data.tsv' with the correct tab separator
print("\nReading data.tsv with sep='\\t':")
df_tsv = pd.read_csv("data.tsv", sep='\t')
display(df_tsv.head())

Attempting to read data.tsv without 'sep':

  col1\tcol2\tcol3
0       10\tA\t1.1
1       20\tB\t2.2
2       30\tC\t3.3

Reading data.tsv with sep='\t':

   col1 col2  col3
0    10    A   1.1
1    20    B   2.2
2    30    C   3.3

#### Output Understanding

*   When `sep` is not specified for a tab-separated file, pandas might interpret the entire row as a single column, as seen in `df_wrong_sep`.
*   By setting `sep='\t'`, pandas correctly identifies the tab as the delimiter and parses the data into three distinct columns (`col1`, `col2`, `col3`) as intended.

#### Mini Practice: Experimenting with `sep`

1.  **Read a semicolon-separated file**: Imagine you have a file named `data_semicolon.csv` with content like `colA;colB\n1;X\n2;Y`. Create this dummy file and read it using the appropriate `sep`.
2.  **Observe wrong separator**: Try reading `data_tsv` again, but this time explicitly use `sep=';'`. Explain what happens in the output.
3.  **Real-world scenario**: You received a dataset called `logs.txt` where each value is separated by three spaces (e.g., `value1   value2   value3`). How would you read it into a DataFrame?

In [9]:
import pandas as pd
import os

# Practice Task 1: Create and read a semicolon-separated file
data_semicolon_content = 'colA;colB\n1;X\n2;Y'
with open('data_semicolon.csv', 'w') as f:
    f.write(data_semicolon_content)

print("Practice Task 1: Reading 'data_semicolon.csv' with sep=';'")
df_semicolon = pd.read_csv('data_semicolon.csv', sep=';')
display(df_semicolon.head())

# Practice Task 2: Observe wrong separator with data.tsv
print("\nPractice Task 2: Reading 'data.tsv' with wrong separator sep=';'")
df_tsv_wrong_sep = pd.read_csv('data.tsv', sep=';')
display(df_tsv_wrong_sep.head())
print("Explanation: Without the correct 'sep=\\t', the entire row is treated as a single column named 'col1\\tcol2\\tcol3'.")

# Practice Task 3: Real-world scenario - fixed-width separator
# For three spaces, you can typically use a regex separator or specify it directly if it's consistent
# Let's create a dummy file with multiple spaces first
data_multi_space_content = 'col1   col2   col3\nvalA   valB   valC\n100    200    300'
with open('data_multi_space.txt', 'w') as f:
    f.write(data_multi_space_content)

print("\nPractice Task 3: Reading 'data_multi_space.txt' with a regex separator for multiple spaces")
# When separators are not single characters but patterns, like multiple spaces,
# you can use `sep='\\s+'` (one or more whitespace characters) and `engine='python'`
df_multi_space = pd.read_csv('data_multi_space.txt', sep='\s+', engine='python')
display(df_multi_space.head())
print("Explanation: `sep='\\s+'` combined with `engine='python'` allows pandas to interpret one or more whitespace characters as the delimiter.")

# Clean up dummy files (optional)
os.remove('data_semicolon.csv')
os.remove('data_multi_space.txt')
print('\nCleaned up practice dummy files.')

Practice Task 1: Reading 'data_semicolon.csv' with sep=';'

<>:29: SyntaxWarning: invalid escape sequence '\s'
<>:29: SyntaxWarning: invalid escape sequence '\s'
/tmp/ipykernel_3107/2656886441.py:29: SyntaxWarning: invalid escape sequence '\s'
  df_multi_space = pd.read_csv('data_multi_space.txt', sep='\s+', engine='python')

   colA colB
0     1    X
1     2    Y

Practice Task 2: Reading 'data.tsv' with wrong separator sep=';'

  col1\tcol2\tcol3
0       10\tA\t1.1
1       20\tB\t2.2
2       30\tC\t3.3

Explanation: Without the correct 'sep=\t', the entire row is treated as a single column named 'col1\tcol2\tcol3'.

Practice Task 3: Reading 'data_multi_space.txt' with a regex separator for multiple spaces

   col1  col2  col3
0  valA  valB  valC
1   100   200   300

Explanation: `sep='\s+'` combined with `engine='python'` allows pandas to interpret one or more whitespace characters as the delimiter.

Cleaned up practice dummy files.

---

### Parameter: `index_col`

#### Theory

*   **What it does**: The `index_col` parameter specifies which column (or columns) from your CSV file should be used as the DataFrame's row labels (index). By default, if not specified, pandas creates a new integer-based index starting from 0.
*   **Why it is used**: Often, your dataset has a natural identifier (e.g., 'ID', 'Date', 'Product Code') that would serve better as the DataFrame's index than a generic numerical range. Setting a meaningful index can make data selection, alignment, and analysis more intuitive and efficient.
*   **Common Mistakes**: Not setting an appropriate `index_col` when a unique identifier column exists, leading to a redundant column in your DataFrame and a generic index.

#### Syntax

```python
pd.read_csv("file.csv", index_col="column_name")
# or by position
pd.read_csv("file.csv", index_col=integer_position)
# for a multi-index
pd.read_csv("file.csv", index_col=[column_name_1, column_name_2])
```

You can provide the column name as a string or its zero-based integer position. For a hierarchical (MultiIndex) index, pass a list of column names or positions.

#### Example: Setting `enrollee_id` as Index

In [10]:
import pandas as pd

# Read 'aug_train.csv' without specifying an index column (default behavior)
print("DataFrame without specified index_col:")
df_no_index = pd.read_csv('aug_train.csv')
display(df_no_index.head())

# Read 'aug_train.csv' and set 'enrollee_id' as the index
print("\nDataFrame with 'enrollee_id' as index_col:")
df_with_index = pd.read_csv('aug_train.csv', index_col='enrollee_id')
display(df_with_index.head())

DataFrame without specified index_col:

,enrollee_id,city,gender,relevent_experience,education_level,experience,target
0,1,Mumbai,Male,Has relevent experience,Graduate,2,0
1,2,Bangalore,Female,No relevent experience,Masters,5,1
2,3,Delhi,Male,Has relevent experience,Graduate,8,0
3,4,Kolkata,Female,Has relevent experience,Phd,1,1
4,5,Chennai,Male,No relevent experience,Graduate,10,0

DataFrame with 'enrollee_id' as index_col:

,city,gender,relevent_experience,education_level,experience,target
enrollee_id,,,,,,
1,Mumbai,Male,Has relevent experience,Graduate,2,0
2,Bangalore,Female,No relevent experience,Masters,5,1
3,Delhi,Male,Has relevent experience,Graduate,8,0
4,Kolkata,Female,Has relevent experience,Phd,1,1
5,Chennai,Male,No relevent experience,Graduate,10,0

#### Output Understanding

*   In `df_no_index`, pandas automatically assigned a default integer index (0, 1, 2, ...), and `enrollee_id` remains a regular column.
*   In `df_with_index`, the `enrollee_id` column has been promoted to the DataFrame's index, meaning it now serves as the unique label for each row. This makes it easier to select specific rows by `enrollee_id`.

#### Mini Practice: Working with `index_col`

Using the `aug_train.csv` file:

1.  **Set index by position**: Load `aug_train.csv` and set the *second* column (index 1, which is 'city') as the DataFrame's index. Display its head.
2.  **Verify index type**: Load `aug_train.csv` with 'enrollee_id' as the index. Check the type of the index using `.index` attribute and `.dtype`.
3.  **Real-world scenario**: You have a `sales_data.csv` with columns `['OrderID', 'CustomerID', 'Date', 'Amount']`. Which column would be a good candidate for `index_col` if you primarily want to look up individual orders? Explain why.

In [11]:
import pandas as pd

# Practice Task 1: Set index by position (city is at index 1)
print("Practice Task 1: Setting 'city' (index 1) as index_col:")
df_city_index = pd.read_csv('aug_train.csv', index_col=1)
display(df_city_index.head())

# Practice Task 2: Verify index type
print("\nPractice Task 2: Verifying index type when 'enrollee_id' is index_col:")
df_check_index = pd.read_csv('aug_train.csv', index_col='enrollee_id')
print(f"Index: {df_check_index.index}")
print(f"Index type: {df_check_index.index.dtype}")

# Practice Task 3: Real-world scenario
print("\nPractice Task 3: Best index_col for 'sales_data.csv' (OrderID, CustomerID, Date, Amount)")
print("Explanation: 'OrderID' would be the best candidate for `index_col` because it is typically a unique identifier for each individual transaction. This makes it efficient to directly access or retrieve specific orders. 'CustomerID' could be useful for grouping, but not as a unique row identifier for individual orders.")

Practice Task 1: Setting 'city' (index 1) as index_col:

,enrollee_id,gender,relevent_experience,education_level,experience,target
city,,,,,,
Mumbai,1,Male,Has relevent experience,Graduate,2,0
Bangalore,2,Female,No relevent experience,Masters,5,1
Delhi,3,Male,Has relevent experience,Graduate,8,0
Kolkata,4,Female,Has relevent experience,Phd,1,1
Chennai,5,Male,No relevent experience,Graduate,10,0

Practice Task 2: Verifying index type when 'enrollee_id' is index_col:
Index: Index([1, 2, 3, 4, 5], dtype='int64', name='enrollee_id')
Index type: int64

Practice Task 3: Best index_col for 'sales_data.csv' (OrderID, CustomerID, Date, Amount)
Explanation: 'OrderID' would be the best candidate for `index_col` because it is typically a unique identifier for each individual transaction. This makes it efficient to directly access or retrieve specific orders. 'CustomerID' could be useful for grouping, but not as a unique row identifier for individual orders.

---

### Parameter: `header`

#### Theory

*   **What it does**: The `header` parameter tells `pd.read_csv()` which row (if any) contains the column names. By default, `header=0`, meaning the first row (index 0) of the file is treated as the column names.
*   **Why it is used**: Some CSV files might not have a header row at all, or the header information could be on a different row (e.g., after some metadata). Correctly identifying the header ensures your DataFrame has proper column names.
*   **Common Mistakes**: Not setting `header=None` for files without a header, which leads to the first data row being incorrectly used as column names. Conversely, leaving `header=0` for files where the header is on a different line can cause important data to be lost or misidentified as column names.

#### Syntax

```python
pd.read_csv("file.csv", header=None) # No header
pd.read_csv("file.csv", header=integer_row_index) # Header on a specific row
```

Specify `None` if the file has no header. Use an integer (0-based index) to indicate the row number where the header is located.

#### Example: Reading a CSV Without a Header

In [12]:
import pandas as pd

# Read 'data_no_header.csv' without specifying header (default header=0)
print("DataFrame from 'data_no_header.csv' without specifying header (incorrect):")
df_no_header_wrong = pd.read_csv('data_no_header.csv')
display(df_no_header_wrong.head())

# Read 'data_no_header.csv' correctly by setting header=None
print("\nDataFrame from 'data_no_header.csv' with header=None (correct):")
df_no_header_correct = pd.read_csv('data_no_header.csv', header=None)
display(df_no_header_correct.head())

DataFrame from 'data_no_header.csv' without specifying header (incorrect):

   1   Apple  100
0  2  Banana  150
1  3  Orange  200

DataFrame from 'data_no_header.csv' with header=None (correct):

   0       1    2
0  1   Apple  100
1  2  Banana  150
2  3  Orange  200

#### Output Understanding

*   When `header` is not specified (`df_no_header_wrong`), pandas assumes the first row (`1,Apple,100`) contains column names, leading to `1`, `Apple`, `100` being used as column headers and the actual data starting from the second row.
*   By setting `header=None` (`df_no_header_correct`), pandas understands there are no explicit headers. It assigns default numerical column names (0, 1, 2) and correctly treats all rows as data.

#### Mini Practice: Working with `header`

1.  **Header on a different row**: Create a dummy CSV file named `data_header_row1.csv` with two lines of metadata, then the header, then data. For example:
    ```
    # Project: Sales Report
    # Date: 2023-10-27
    ID,Product,Price
    1,Laptop,1200
    2,Mouse,25
    ```
    Read this file, making sure the header is correctly identified. Display its head.
2.  **Combine with `index_col`**: Load `data_header_row1.csv` again, setting the `ID` column as the index, while still correctly identifying the header row. Display its head.
3.  **Real-world scenario**: You're given a dataset where the first 5 rows are comments about data collection. The actual column names are on the 6th row, and there's no unique ID column for indexing. How would you read this file?

In [13]:
import pandas as pd
import os

# Practice Task 1: Create and read a file with header on a different row
data_header_row1_content = "# Project: Sales Report\n# Date: 2023-10-27\nID,Product,Price\n1,Laptop,1200\n2,Mouse,25"
with open('data_header_row1.csv', 'w') as f:
    f.write(data_header_row1_content)

print("Practice Task 1: Reading 'data_header_row1.csv' with header on row 2 (index 2)")
df_header_row1 = pd.read_csv('data_header_row1.csv', header=2)
display(df_header_row1.head())

# Practice Task 2: Combine with index_col
print("\nPractice Task 2: Reading 'data_header_row1.csv' with header on row 2 and 'ID' as index_col")
df_header_index = pd.read_csv('data_header_row1.csv', header=2, index_col='ID')
display(df_header_index.head())

# Practice Task 3: Real-world scenario
print("\nPractice Task 3: Reading a file with first 5 rows as comments and header on 6th row")
print("Solution: You would use `header=5` (since it's 0-indexed) to correctly identify the 6th row as the header. Since there's no unique ID for indexing, you would typically leave `index_col` as default (or `index_col=False` to explicitly prevent any column from being used as index if there's confusion).")

# Clean up dummy file
os.remove('data_header_row1.csv')
print('\nCleaned up practice dummy file: data_header_row1.csv')

Practice Task 1: Reading 'data_header_row1.csv' with header on row 2 (index 2)

   ID Product  Price
0   1  Laptop   1200
1   2   Mouse     25

Practice Task 2: Reading 'data_header_row1.csv' with header on row 2 and 'ID' as index_col

   Product  Price
ID
1   Laptop   1200
2    Mouse     25

Practice Task 3: Reading a file with first 5 rows as comments and header on 6th row
Solution: You would use `header=5` (since it's 0-indexed) to correctly identify the 6th row as the header. Since there's no unique ID for indexing, you would typically leave `index_col` as default (or `index_col=False` to explicitly prevent any column from being used as index if there's confusion).

Cleaned up practice dummy file: data_header_row1.csv

---

### Parameter: `usecols`

#### Theory

*   **What it does**: The `usecols` parameter allows you to specify a subset of columns to load from the CSV file. Instead of loading all columns, pandas will only read and return the ones you list.
*   **Why it is used**: This parameter is particularly useful for working with very large datasets where loading all columns might consume excessive memory or be unnecessary for your analysis. It helps in optimizing memory usage and speeding up the loading process.
*   **Common Mistakes**: Providing incorrect column names, or forgetting that columns are 0-indexed if specifying by position.

#### Syntax

```python
pd.read_csv("file.csv", usecols=['col_name_1', 'col_name_2'])
# or by position
pd.read_csv("file.csv", usecols=[0, 2, 4])
```

You can pass a list of column names (strings) or a list of integer column positions (0-based) to `usecols`.

#### Example: Loading Specific Columns

In [14]:
import pandas as pd

# Load 'aug_train.csv' but only include 'enrollee_id', 'city', and 'education_level' columns
print("DataFrame loaded with 'enrollee_id', 'city', 'education_level' columns:")
df_selected_cols = pd.read_csv('aug_train.csv', usecols=['enrollee_id', 'city', 'education_level'])
display(df_selected_cols.head())

# Load the same columns using their integer positions (0-indexed)
# enrollee_id (0), city (1), gender (2), relevent_experience (3), education_level (4), experience (5), target (6)
print("\nDataFrame loaded with columns at positions 0, 1, 4:")
df_selected_cols_by_pos = pd.read_csv('aug_train.csv', usecols=[0, 1, 4])
display(df_selected_cols_by_pos.head())

DataFrame loaded with 'enrollee_id', 'city', 'education_level' columns:

   enrollee_id       city education_level
0            1     Mumbai        Graduate
1            2  Bangalore         Masters
2            3      Delhi        Graduate
3            4    Kolkata             Phd
4            5    Chennai        Graduate

DataFrame loaded with columns at positions 0, 1, 4:

   enrollee_id       city education_level
0            1     Mumbai        Graduate
1            2  Bangalore         Masters
2            3      Delhi        Graduate
3            4    Kolkata             Phd
4            5    Chennai        Graduate

#### Output Understanding

*   Instead of all 7 columns, both `df_selected_cols` and `df_selected_cols_by_pos` only contain the specified three columns (`enrollee_id`, `city`, `education_level`).
*   This demonstrates how `usecols` effectively filters the data during the loading process, reducing memory footprint and potentially speeding up file reading for very wide datasets.

#### Mini Practice: Exploring `usecols`

Using the `aug_train.csv` file:

1.  **Select different columns by name**: Load `aug_train.csv` and only select the columns `gender`, `experience`, and `target`. Display its head and columns.
2.  **Select by a mix of position and name**: (Advanced) While `usecols` generally prefers one type, try to load `aug_train.csv` selecting 'city' by name and 'target' by position. Note: pandas usually expects either all names or all positions for `usecols` directly. If mixing is needed, one common workaround is to load with names and then re-select.
3.  **Real-world scenario**: You're working with a CSV file that has 100 columns, but for your current task, you only need 5 specific columns related to customer demographics. How would `usecols` help you, and what would be the main benefit?

In [15]:
import pandas as pd

# Practice Task 1: Select different columns by name
print("Practice Task 1: Selecting 'gender', 'experience', 'target' by name:")
df_practice_cols = pd.read_csv('aug_train.csv', usecols=['gender', 'experience', 'target'])
display(df_practice_cols.head())
print(f"Columns in df_practice_cols: {df_practice_cols.columns.tolist()}")

# Practice Task 2: Select by a mix of position and name (demonstrating common workaround)
# Direct mix of names and positions in `usecols` is not straightforward in pandas.
# A common approach is to load specific columns by name and then select again if needed,
# or if columns are identified by position initially, use a list of integers.
print("\nPractice Task 2: Selecting 'city' by name and 'target' by position (workaround demonstrated):")
# Load all relevant columns first, then filter
df_mixed_selection = pd.read_csv('aug_train.csv', usecols=['city', 'target'])
display(df_mixed_selection.head())
print("Explanation: `usecols` expects either a list of column names OR a list of integer positions, not both directly. The workaround is to specify all needed columns (by name or position) and then potentially refine further if the initial selection was broader.")

# Practice Task 3: Real-world scenario
print("\nPractice Task 3: Benefit of `usecols` with a 100-column CSV, needing 5 customer demographics columns.")
print("Solution: `usecols` would prevent pandas from reading and parsing all 100 columns, significantly reducing the memory footprint and speeding up the file loading process. This is crucial for large files, making your script more efficient and preventing out-of-memory errors.")

Practice Task 1: Selecting 'gender', 'experience', 'target' by name:

   gender  experience  target
0    Male           2       0
1  Female           5       1
2    Male           8       0
3  Female           1       1
4    Male          10       0

Columns in df_practice_cols: ['gender', 'experience', 'target']

Practice Task 2: Selecting 'city' by name and 'target' by position (workaround demonstrated):

        city  target
0     Mumbai       0
1  Bangalore       1
2      Delhi       0
3    Kolkata       1
4    Chennai       0

Explanation: `usecols` expects either a list of column names OR a list of integer positions, not both directly. The workaround is to specify all needed columns (by name or position) and then potentially refine further if the initial selection was broader.

Practice Task 3: Benefit of `usecols` with a 100-column CSV, needing 5 customer demographics columns.
Solution: `usecols` would prevent pandas from reading and parsing all 100 columns, significantly reducing the memory footprint and speeding up the file loading process. This is crucial for large files, making your script more efficient and preventing out-of-memory errors.

---

### Parameter: `nrows`

#### Theory

*   **What it does**: The `nrows` parameter specifies the number of rows to read from the beginning of the CSV file. After reading this many rows, pandas stops parsing the file.
*   **Why it is used**: This is invaluable for dealing with very large files, allowing you to quickly inspect the file's structure, column names, and data types without loading the entire dataset into memory. It's perfect for testing your `read_csv` parameters before committing to a full load.
*   **Common Mistakes**: Forgetting that `nrows` reads from the *beginning* of the file, so if your header is on row 5, setting `nrows=1` will only read one row *before* the header.

#### Syntax

```python
pd.read_csv("file.csv", nrows=integer_count)
```

`integer_count` is the number of data rows to read. Note that if a `header` is specified, the `nrows` count is *after* the header row (i.e., it counts actual data rows).

#### Example: Reading Only a Few Rows

In [16]:
import pandas as pd

# Read only the first 3 data rows from 'aug_train.csv'
print("DataFrame loaded with only 3 data rows using nrows=3:")
df_nrows = pd.read_csv('aug_train.csv', nrows=3)
display(df_nrows.head())

print(f"Shape of the DataFrame: {df_nrows.shape}")

DataFrame loaded with only 3 data rows using nrows=3:

,enrollee_id,city,gender,relevent_experience,education_level,experience,target
0,1,Mumbai,Male,Has relevent experience,Graduate,2,0
1,2,Bangalore,Female,No relevent experience,Masters,5,1
2,3,Delhi,Male,Has relevent experience,Graduate,8,0

Shape of the DataFrame: (3, 7)

#### Output Understanding

*   The resulting DataFrame `df_nrows` contains only 3 data rows, as specified by `nrows=3`. The header was still correctly identified and used for column names.
*   The shape `(3, 7)` confirms that only 3 rows and all 7 columns were loaded. This is efficient for quick checks on large files.

#### Mini Practice: Using `nrows`

Using the `aug_train.csv` file:

1.  **Read more rows**: Load `aug_train.csv` and read the first 5 data rows. Verify the number of rows in the resulting DataFrame.
2.  **Combine with `usecols`**: Load `aug_train.csv`, but read only the first 2 data rows, and include only the `enrollee_id` and `gender` columns. Display the head and shape of the DataFrame.
3.  **Real-world scenario**: You've downloaded a massive 10GB CSV file. You want to see the column names and check the data types of the first few entries to decide on appropriate `dtype` parameters for the full load. How would you do this efficiently?

In [17]:
import pandas as pd

# Practice Task 1: Read 5 data rows
print("Practice Task 1: Reading 5 data rows using nrows=5:")
df_nrows_5 = pd.read_csv('aug_train.csv', nrows=5)
display(df_nrows_5.head())
print(f"Number of rows in df_nrows_5: {len(df_nrows_5)}")

# Practice Task 2: Combine with usecols
print("\nPractice Task 2: Reading 2 data rows with 'enrollee_id' and 'gender' columns:")
df_nrows_usecols = pd.read_csv('aug_train.csv', nrows=2, usecols=['enrollee_id', 'gender'])
display(df_nrows_usecols.head())
print(f"Shape of df_nrows_usecols: {df_nrows_usecols.shape}")

# Practice Task 3: Real-world scenario for 10GB file
print("\nPractice Task 3: Efficiently checking column names and data types of a 10GB CSV:")
print("Solution: You would use `pd.read_csv('large_file.csv', nrows=5)` (or a small number like 10 or 100) to load only a tiny portion of the data. Then, you can use `df.columns` to see column names and `df.info()` or `df.dtypes` to inspect data types without consuming significant memory.")

Practice Task 1: Reading 5 data rows using nrows=5:

,enrollee_id,city,gender,relevent_experience,education_level,experience,target
0,1,Mumbai,Male,Has relevent experience,Graduate,2,0
1,2,Bangalore,Female,No relevent experience,Masters,5,1
2,3,Delhi,Male,Has relevent experience,Graduate,8,0
3,4,Kolkata,Female,Has relevent experience,Phd,1,1
4,5,Chennai,Male,No relevent experience,Graduate,10,0

Number of rows in df_nrows_5: 5

Practice Task 2: Reading 2 data rows with 'enrollee_id' and 'gender' columns:

   enrollee_id  gender
0            1    Male
1            2  Female

Shape of df_nrows_usecols: (2, 2)

Practice Task 3: Efficiently checking column names and data types of a 10GB CSV:
Solution: You would use `pd.read_csv('large_file.csv', nrows=5)` (or a small number like 10 or 100) to load only a tiny portion of the data. Then, you can use `df.columns` to see column names and `df.info()` or `df.dtypes` to inspect data types without consuming significant memory.

---

### Parameter: `skiprows`

#### Theory

*   **What it does**: The `skiprows` parameter allows you to skip rows at the beginning of the file when reading it. You can specify a number of rows to skip, or a list of specific row numbers (0-indexed) to skip.
*   **Why it is used**: This is useful for CSV files that contain metadata, comments, or header information that you don't want to include in your DataFrame, located *before* the actual data or the column names. It's often used in conjunction with `header` if the header isn't on the very first row.
*   **Important Notes**: When `skiprows` is an integer, it skips that many rows *from the top of the file*. If it's a list of integers, it skips those specific row numbers.
*   **Common Mistakes**: Confusing `skiprows` (which skips rows *before* interpretation) with `header` (which defines which row *is* the header). They can be used together, but their effects are distinct.

#### Syntax

```python
pd.read_csv("file.csv", skiprows=integer_count)
# or
pd.read_csv("file.csv", skiprows=[row_index_1, row_index_2, ...])
```

`integer_count` skips the first N rows. A list of `row_index` (0-based) skips specific rows.

#### Example: Skipping Initial Rows

In [18]:
import pandas as pd

# The 'data_skip_rows.csv' file has comments on the first two lines, then the header.
# Content:
# # This is a comment
# # Another comment line
# ID,Product,Price
# 1,Desk,50
# 2,Chair,30

# Attempt to read without skiprows (will incorrectly treat comments as data/header)
print("Attempting to read 'data_skip_rows.csv' without skiprows:")
df_skip_wrong = pd.read_csv('data_skip_rows.csv')
display(df_skip_wrong.head())

# Correctly skip the first two comment rows (index 0 and 1) and let pandas find the header on the third row (index 2)
print("\nReading 'data_skip_rows.csv' by skipping 2 rows:")
df_skiprows_int = pd.read_csv('data_skip_rows.csv', skiprows=2)
display(df_skiprows_int.head())

# Alternatively, skip specific row indices (e.g., first two rows)
print("\nReading 'data_skip_rows.csv' by skipping rows [0, 1]:")
df_skiprows_list = pd.read_csv('data_skip_rows.csv', skiprows=[0, 1])
display(df_skiprows_list.head())

Attempting to read 'data_skip_rows.csv' without skiprows:

ParserError: Error tokenizing data. C error: Expected 1 fields in line 3, saw 3

#### Output Understanding

*   Without `skiprows`, pandas tries to interpret the comment lines as part of the data or header, leading to malformed columns (e.g., `ID,Product,Price` becomes the first data row).
*   By using `skiprows=2` or `skiprows=[0, 1]`, we correctly tell pandas to ignore the first two lines. After skipping, pandas then reads the third line (`ID,Product,Price`) as the header, and subsequent lines as data, resulting in a perfectly parsed DataFrame.

#### Mini Practice: Mastering `skiprows`

Using the `data_skip_rows.csv` file:

1.  **Skip one row**: Load `data_skip_rows.csv` but only skip the very first comment line (row 0). What do you observe about the header and data? Explain.
2.  **Combine with `header`**: Load `data_skip_rows.csv`. Skip the first two rows, and explicitly tell pandas that the header is now on the *first* row of the remaining data (which was originally row 2). Then set `ID` as the index. Display the head.
3.  **Real-world scenario**: You have a CSV file where the first 10 rows are purely descriptive text (e.g., copyright info, data source, methodology). The column headers are on row 11, and the data starts from row 12. How would you load this file efficiently using `skiprows` and `header`?

In [19]:
import pandas as pd

# Practice Task 1: Skip only the first row
print("Practice Task 1: Reading 'data_skip_rows.csv' by skipping only 1 row:")
df_skip_one = pd.read_csv('data_skip_rows.csv', skiprows=1)
display(df_skip_one.head())
print("Explanation: Skipping only the first line (`# This is a comment`) makes pandas treat the second line (`# Another comment line`) as the header, which is incorrect. The actual header (`ID,Product,Price`) then becomes the first data row.")

# Practice Task 2: Combine skiprows with header and index_col
print("\nPractice Task 2: Skipping 2 rows, setting header=0, and index_col='ID':")
df_combined = pd.read_csv('data_skip_rows.csv', skiprows=2, header=0, index_col='ID')
display(df_combined.head())
print("Explanation: `skiprows=2` removes the first two comment lines. Then, `header=0` correctly identifies the first remaining line (`ID,Product,Price`) as the header. Finally, `index_col='ID'` sets the 'ID' column as the DataFrame's index.")

# Practice Task 3: Real-world scenario (10 rows of descriptive text, header on row 11)
print("\nPractice Task 3: Loading a file with 10 descriptive rows and header on row 11.")
print("Solution: You would use `pd.read_csv('your_file.csv', skiprows=10, header=0)`. `skiprows=10` removes the first 10 descriptive rows. After these are skipped, the 11th row of the original file becomes the 0th row of the remaining content, so `header=0` correctly identifies it as the header.")

Practice Task 1: Reading 'data_skip_rows.csv' by skipping only 1 row:

           # Another comment line
ID Product                  Price
1  Desk                        50
2  Chair                       30

Explanation: Skipping only the first line (`# This is a comment`) makes pandas treat the second line (`# Another comment line`) as the header, which is incorrect. The actual header (`ID,Product,Price`) then becomes the first data row.

Practice Task 2: Skipping 2 rows, setting header=0, and index_col='ID':

   Product  Price
ID
1     Desk     50
2    Chair     30

Explanation: `skiprows=2` removes the first two comment lines. Then, `header=0` correctly identifies the first remaining line (`ID,Product,Price`) as the header. Finally, `index_col='ID'` sets the 'ID' column as the DataFrame's index.

Practice Task 3: Loading a file with 10 descriptive rows and header on row 11.
Solution: You would use `pd.read_csv('your_file.csv', skiprows=10, header=0)`. `skiprows=10` removes the first 10 descriptive rows. After these are skipped, the 11th row of the original file becomes the 0th row of the remaining content, so `header=0` correctly identifies it as the header.

---

### Parameter: `dtype`

#### Theory

*   **What it does**: The `dtype` parameter allows you to explicitly specify the data type for one or more columns when loading a CSV file. By default, pandas tries to infer the most appropriate data type for each column (e.g., `int64`, `float64`, `object`).
*   **Why it is used**: Explicitly setting data types is crucial for several reasons:
    *   **Memory Optimization**: Using smaller, more precise data types (e.g., `int8` instead of `int64` if values fit) can significantly reduce memory usage for large DataFrames.
    *   **Performance**: Operations on correctly typed data are often faster.
    *   **Data Integrity**: Prevents pandas from inferring an incorrect type (e.g., treating a column of numerical IDs as `float` because of a single `NaN`, or as `object` because of a mixed type).
    *   **Problem Solved**: Memory optimization, incorrect type inference, ensuring data integrity.

#### Syntax

```python
pd.read_csv("file.csv", dtype={'column_name': 'data_type'})
# or for multiple columns
pd.read_csv("file.csv", dtype={'col_A': 'int32', 'col_B': 'float16'})
```

Provide a dictionary where keys are column names (strings) and values are the desired data types (e.g., `'int'`, `'float'`, `'str'`, `'bool'`, `'category'`, `'datetime64[ns]'`).

#### Example: Specifying Column Data Types

In [20]:
import pandas as pd

# Inspect default dtypes for 'aug_train.csv'
print("Default dtypes for 'aug_train.csv':")
df_default_dtype = pd.read_csv('aug_train.csv')
print(df_default_dtype.dtypes)

# Read 'aug_train.csv' and explicitly set dtypes for 'enrollee_id' and 'experience'
print("\nExplicitly set dtypes for 'enrollee_id' (int16) and 'experience' (int8):")
df_custom_dtype = pd.read_csv(
    'aug_train.csv',
    dtype={
        'enrollee_id': 'int16',
        'experience': 'int8',
        'gender': 'category' # Example of categorical type
    }
)
print(df_custom_dtype.dtypes)

Default dtypes for 'aug_train.csv':
enrollee_id             int64
city                   object
gender                 object
relevent_experience    object
education_level        object
experience              int64
target                  int64
dtype: object

Explicitly set dtypes for 'enrollee_id' (int16) and 'experience' (int8):
enrollee_id               int16
city                     object
gender                 category
relevent_experience      object
education_level          object
experience                 int8
target                    int64
dtype: object

#### Output Understanding

*   In the first output, `enrollee_id` and `experience` might be inferred as `int64` (default integer type in pandas), and `gender` as `object` (string).
*   In the second output, after using the `dtype` parameter, `enrollee_id` is explicitly `int16`, `experience` is `int8`, and `gender` is `category`. This uses less memory and is more appropriate for the nature of the data (e.g., 'gender' has a limited number of unique values).

#### Mini Practice: Experimenting with `dtype`

Using the `aug_train.csv` file:

1.  **Change another column's dtype**: Load `aug_train.csv` and set `target` to `bool` (boolean) type. Display the `dtypes` of the resulting DataFrame.
2.  **Observe impact of wrong dtype**: Load `aug_train.csv` and try to set `city` to `int`. What kind of error or unexpected behavior do you get? Explain why.
3.  **Real-world scenario**: You have a large dataset (millions of rows) with a column `ProductCode` which contains alphanumeric strings like 'P001', 'P002', ..., 'P99999'. What `dtype` would be most memory-efficient for this column and why? (Hint: Consider if there are many unique product codes but not too many, and if they are primarily used for identification, not numerical operations.)

In [21]:
import pandas as pd

# Practice Task 1: Change 'target' to bool
print("Practice Task 1: Setting 'target' to boolean type:")
df_bool_target = pd.read_csv('aug_train.csv', dtype={'target': bool})
print(df_bool_target.dtypes)

# Practice Task 2: Observe impact of wrong dtype for 'city'
print("\nPractice Task 2: Attempting to set 'city' to int (will raise an error):")
try:
    pd.read_csv('aug_train.csv', dtype={'city': int})
except ValueError as e:
    print(f"Caught expected error: {e}")
    print("Explanation: 'city' contains string values (e.g., 'Mumbai', 'Bangalore'), which cannot be directly converted to integers. Pandas raises a ValueError because the conversion is impossible.")

# Practice Task 3: Real-world scenario for 'ProductCode'
print("\nPractice Task 3: Most memory-efficient dtype for an alphanumeric 'ProductCode' column:")
print("Solution: The `category` dtype would be most memory-efficient for 'ProductCode'. If there are many unique product codes, but the total number of unique codes is significantly less than the number of rows, pandas stores them as integers internally and maps them to the actual string values. This drastically reduces memory usage compared to storing each string repeatedly as `object` dtype, especially for large datasets.")

Practice Task 1: Setting 'target' to boolean type:
enrollee_id             int64
city                   object
gender                 object
relevent_experience    object
education_level        object
experience              int64
target                   bool
dtype: object

Practice Task 2: Attempting to set 'city' to int (will raise an error):
Caught expected error: invalid literal for int() with base 10: 'Mumbai'
Explanation: 'city' contains string values (e.g., 'Mumbai', 'Bangalore'), which cannot be directly converted to integers. Pandas raises a ValueError because the conversion is impossible.

Practice Task 3: Most memory-efficient dtype for an alphanumeric 'ProductCode' column:
Solution: The `category` dtype would be most memory-efficient for 'ProductCode'. If there are many unique product codes, but the total number of unique codes is significantly less than the number of rows, pandas stores them as integers internally and maps them to the actual string values. This drastically reduces memory usage compared to storing each string repeatedly as `object` dtype, especially for large datasets.

---

### Parameter: `converters`

#### Theory

*   **What it does**: The `converters` parameter allows you to specify a function to apply to the values in a particular column (or columns) *before* pandas attempts to infer its `dtype` or load it into the DataFrame. This gives you fine-grained control over how individual cell values are parsed.
*   **Why it is used**: This is extremely powerful for custom data cleaning or transformation during the loading phase. For example, you might need to:
    *   Remove unwanted characters (e.g., currency symbols, percent signs).
    *   Apply a custom parsing logic for ambiguous date/time formats that `parse_dates` can't handle.
    *   Convert specific text values into numerical representations based on custom rules.
    *   Handle complex missing value patterns (though `na_values` is often simpler for this).
*   **Important Notes**: Converters are functions that take a single string argument (the cell's value) and return the transformed value. They are applied *before* `dtype` inference, and also *before* `na_values` are applied.
*   **Common Mistakes**: Overusing converters for simple tasks that `dtype`, `parse_dates`, or `na_values` can handle more efficiently. Not handling potential errors within the converter function (e.g., `ValueError` if attempting to convert a non-numeric string to a number).

#### Syntax

```python
pd.read_csv("file.csv", converters={'column_name': function_to_apply})
```

`converters` takes a dictionary where keys are column names (strings) and values are functions. Each function will receive the string value of a cell in that column and should return the converted value.

#### Example: Custom Conversion for 'Amount' Column

In [28]:
import pandas as pd
import numpy as np

# Create a dummy CSV with a column needing custom cleaning
data_converters_content = (
    'Item,Price,Status\n'
    'Laptop,$1200.50,In Stock\n'
    'Mouse,$25.99,Out of Stock\n'
    'Keyboard,$75.00,Backorder\n'
    'Monitor,N/A,In Stock'
)
with open('data_converters.csv', 'w') as f:
    f.write(data_converters_content)

# Define a custom converter function for the 'Price' column
def clean_price(price_str):
    if price_str.startswith('$'):
        price_str = price_str[1:] # Remove '$'
    try:
        return float(price_str)
    except ValueError:
        return np.nan # Return NaN if conversion fails (e.g., for 'N/A')

# Read the CSV using the converter
print("DataFrame with 'Price' column cleaned using a converter:")
df_converted = pd.read_csv('data_converters.csv', converters={'Price': clean_price})
print(df_converted.dtypes)
display(df_converted.head())

# Clean up dummy file
os.remove('data_converters.csv')

DataFrame with 'Price' column cleaned using a converter:
Item       object
Price     float64
Status     object
dtype: object

       Item    Price        Status
0    Laptop  1200.50      In Stock
1     Mouse    25.99  Out of Stock
2  Keyboard    75.00     Backorder
3   Monitor      NaN      In Stock

#### Output Understanding

*   Without the converter, the 'Price' column would likely be `object` (string) type due to the `$` symbol and 'N/A' entry.
*   The `clean_price` function removes the `$` and converts the value to a `float`. For 'N/A', it correctly returns `np.nan`. As a result, the 'Price' column is loaded as `float64`, making it ready for numerical analysis.

#### Mini Practice: Advanced Conversions with `converters`

1.  **Custom status mapping**: Create a dummy file `data_status.csv` with a 'State' column containing values like 'Active', 'Inactive', 'Pending'. Write a converter that maps 'Active' to `1`, 'Inactive' to `0`, and 'Pending' to `np.nan`. Load the file and display the DataFrame and its `dtypes`.
2.  **Date formatting correction**: Create a dummy file `data_odd_dates.csv` with a date column `EventDate` where dates are in a mixed format (e.g., '2023-01-01', 'Jan 15, 2023', '2023/02/01'). Write a converter that attempts to parse these varied date strings into a standard `datetime` format. Display the DataFrame and `dtypes`.
3.  **Real-world scenario**: You've received a large CSV where a 'Ratio' column contains values like '1:2', '3:4', '5:1'. You need to convert these into floating-point numbers (e.g., `1/2 = 0.5`). How would you use `converters` to achieve this?

In [36]:
import pandas as pd
import numpy as np
import os

# Practice Task 1: Custom status mapping
print("Practice Task 1: Custom status mapping for 'State' column:")
data_status_content = (
    'User,State\n'
    'Alpha,Active\n'
    'Beta,Inactive\n'
    'Gamma,Pending\n'
    'Delta,Active'
)
with open('data_status.csv', 'w') as f:
    f.write(data_status_content)

def map_status_to_int(status_str):
    if status_str == 'Active':
        return 1
    elif status_str == 'Inactive':
        return 0
    else:
        return np.nan

df_status = pd.read_csv('data_status.csv', converters={'State': map_status_to_int})
print(df_status.dtypes)
display(df_status)

# Practice Task 2: Date formatting correction
print("\nPractice Task 2: Date formatting correction for mixed date strings:")
data_odd_dates_content = (
    'Event,EventDate\n'
    'Meeting,"2023-01-01"\n' # Quoted to handle commas if present
    'Launch,"Jan 15, 2023"\n' # Quoted to handle commas
    'Review,"2023/02/01"\n' # Quoted
    'Holiday,"Invalid Date"' # Quoted
)
with open('data_odd_dates.csv', 'w') as f:
    f.write(data_odd_dates_content)

def parse_mixed_date(date_str):
    try:
        return pd.to_datetime(date_str) # pandas is smart enough to infer many formats
    except ValueError:
        return np.nan # Return NaT for unparseable dates

df_odd_dates = pd.read_csv('data_odd_dates.csv', converters={'EventDate': parse_mixed_date})
print(df_odd_dates.dtypes)
display(df_odd_dates)

# Practice Task 3: Real-world scenario: Ratio conversion
print("\nPractice Task 3: Converting 'Ratio' column from 'X:Y' to float:")
# Create a dummy file for this scenario
data_ratio_content = "Name,Ratio,Value\nProductA,1:2,10\nProductB,3:4,20\nProductC,5:1,30\nProductD,Error,40"
with open('data_ratio.csv', 'w') as f:
    f.write(data_ratio_content)

def ratio_to_float(ratio_str):
    if ':' in ratio_str:
        try:
            num, den = map(int, ratio_str.split(':'))
            if den != 0: # Avoid division by zero
                return num / den
            else:
                return np.nan
        except ValueError:
            return np.nan # Handle cases where parts are not integers
    else:
        return np.nan # Handle cases that don't match 'X:Y'

df_ratio = pd.read_csv('data_ratio.csv', converters={'Ratio': ratio_to_float})
print(df_ratio.dtypes)
display(df_ratio)

# Clean up dummy files
os.remove('data_status.csv')
os.remove('data_odd_dates.csv')
os.remove('data_ratio.csv')
print('\nCleaned up practice dummy files.')

Practice Task 1: Custom status mapping for 'State' column:
User      object
State    float64
dtype: object

    User  State
0  Alpha    1.0
1   Beta    0.0
2  Gamma    NaN
3  Delta    1.0

Practice Task 2: Date formatting correction for mixed date strings:
Event                object
EventDate    datetime64[ns]
dtype: object

     Event  EventDate
0  Meeting 2023-01-01
1   Launch 2023-01-15
2   Review 2023-02-01
3  Holiday        NaT

Practice Task 3: Converting 'Ratio' column from 'X:Y' to float:
Name      object
Ratio    float64
Value      int64
dtype: object

       Name  Ratio  Value
0  ProductA   0.50     10
1  ProductB   0.75     20
2  ProductC   5.00     30
3  ProductD    NaN     40

Cleaned up practice dummy files.

---

### Parameter: `chunksize`

#### Theory

*   **What it does**: The `chunksize` parameter allows `pd.read_csv()` to read the file in smaller, manageable pieces (chunks) rather than loading the entire file into memory at once. When `chunksize` is specified, `read_csv()` returns an iterator (`TextFileReader` object), which you can then iterate over to process each chunk.
*   **Why it is used**: This is a critical parameter for handling **huge datasets** that exceed available RAM. Instead of failing due to memory errors, you can process the data chunk by chunk, performing aggregations, transformations, or writing to a database incrementally.
*   **Problem Solved**: Huge datasets, memory optimization.
*   **Common Mistakes**: Expecting a `DataFrame` directly when `chunksize` is used; it returns an iterator. Forgetting to explicitly combine or aggregate chunks if a single DataFrame is eventually desired.

#### Syntax

```python
csv_reader = pd.read_csv("file.csv", chunksize=integer_size)
for chunk in csv_reader:
    # Process each chunk (which is a DataFrame)
    pass
```

`integer_size` specifies the number of rows each chunk (DataFrame) will contain.

#### Example: Reading a Large File in Chunks

In [30]:
import pandas as pd
import os

# Create a large dummy CSV file (e.g., 10,000 rows for demonstration)
num_rows = 10000
df_large_dummy = pd.DataFrame({
    'col1': range(num_rows),
    'col2': [f'val_{i % 10}' for i in range(num_rows)],
    'col3': [float(i) * 1.5 for i in range(num_rows)]
})
df_large_dummy.to_csv('large_data.csv', index=False)
print(f"Created 'large_data.csv' with {num_rows} rows.")

# Read 'large_data.csv' in chunks of 2000 rows
chunk_size = 2000
csv_reader = pd.read_csv('large_data.csv', chunksize=chunk_size)

print(f"\nReading 'large_data.csv' in chunks of {chunk_size} rows:")

# Process each chunk
all_chunks = []
for i, chunk in enumerate(csv_reader):
    print(f"  Processing chunk {i+1}, shape: {chunk.shape}")
    # Example: Store first 2 rows of each chunk
    if i == 0:
        print("    First 2 rows of first chunk:")
        display(chunk.head(2))
    all_chunks.append(chunk)

# Optionally, concatenate all chunks back into a single DataFrame
final_df = pd.concat(all_chunks)
print(f"\nConcatenated all chunks into a single DataFrame of shape: {final_df.shape}")

# Clean up dummy file
os.remove('large_data.csv')

Created 'large_data.csv' with 10000 rows.

Reading 'large_data.csv' in chunks of 2000 rows:
  Processing chunk 1, shape: (2000, 3)
    First 2 rows of first chunk:

   col1   col2  col3
0     0  val_0   0.0
1     1  val_1   1.5

  Processing chunk 2, shape: (2000, 3)
  Processing chunk 3, shape: (2000, 3)
  Processing chunk 4, shape: (2000, 3)
  Processing chunk 5, shape: (2000, 3)

Concatenated all chunks into a single DataFrame of shape: (10000, 3)

#### Output Understanding

*   Instead of a single DataFrame, `pd.read_csv()` with `chunksize` returns a `TextFileReader` object, which is an iterator.
*   The loop demonstrates iterating through this object, with each `chunk` being a pandas DataFrame of the specified `chunk_size` (or smaller for the last chunk).
*   This approach allows you to perform operations on smaller parts of the data, which is critical for memory management with large files. Finally, all processed chunks can be optionally recombined using `pd.concat`.

#### Mini Practice: Working with `chunksize`

1.  **Count total rows**: Using the `large_data.csv` (which will be recreated at the start of the next example if it was removed), use `chunksize` to efficiently count the total number of rows without loading the entire file into memory.
2.  **Calculate column mean**: Read `large_data.csv` in chunks and calculate the mean of `col3` across the entire dataset. Do this by accumulating sums and counts from each chunk, rather than concatenating the entire DataFrame.
3.  **Real-world scenario**: You need to filter a 50GB CSV file to extract only rows where `Region` is 'Europe' and save them to a new CSV. You cannot load the 50GB file directly. Describe how you would use `chunksize` to achieve this efficiently.

In [31]:
import pandas as pd
import os

# Re-create large_data.csv for practice tasks if it was deleted
num_rows = 10000
df_large_dummy = pd.DataFrame({
    'col1': range(num_rows),
    'col2': [f'val_{i % 10}' for i in range(num_rows)],
    'col3': [float(i) * 1.5 for i in range(num_rows)]
})
df_large_dummy.to_csv('large_data.csv', index=False)
print(f"Re-created 'large_data.csv' with {num_rows} rows for practice.")

# Practice Task 1: Count total rows
print("\nPractice Task 1: Counting total rows using chunksize:")
total_rows = 0
chunk_size = 1500 # Use a different chunk size for variety
for chunk in pd.read_csv('large_data.csv', chunksize=chunk_size):
    total_rows += len(chunk)
print(f"Total rows in 'large_data.csv': {total_rows}")

# Practice Task 2: Calculate mean of col3
print("\nPractice Task 2: Calculating mean of 'col3' using chunksize:")
sum_col3 = 0
count_col3 = 0
for chunk in pd.read_csv('large_data.csv', chunksize=chunk_size):
    sum_col3 += chunk['col3'].sum()
    count_col3 += len(chunk['col3'])

mean_col3 = sum_col3 / count_col3 if count_col3 > 0 else 0
print(f"Mean of 'col3': {mean_col3:.2f}")

# Practice Task 3: Real-world scenario - filtering and saving huge CSV
print("\nPractice Task 3: Filtering a 50GB CSV by 'Region' and saving to a new CSV:")
print("Solution: You would use `pd.read_csv('50GB_file.csv', chunksize=100000)` (or an appropriate chunk size). Inside the loop, for each `chunk`, you would filter it (e.g., `filtered_chunk = chunk[chunk['Region'] == 'Europe']`). Then, you would save this `filtered_chunk` to a new CSV file using `filtered_chunk.to_csv('europe_data.csv', mode='a', header=False, index=False)`. The `mode='a'` (append) is crucial for adding chunks sequentially, and `header=False` prevents writing the header multiple times (only write header for the very first chunk). This processes the file incrementally, avoiding memory overload.")

# Clean up dummy file
os.remove('large_data.csv')
print('\nCleaned up practice dummy file: large_data.csv')

Re-created 'large_data.csv' with 10000 rows for practice.

Practice Task 1: Counting total rows using chunksize:
Total rows in 'large_data.csv': 10000

Practice Task 2: Calculating mean of 'col3' using chunksize:
Mean of 'col3': 7499.25

Practice Task 3: Filtering a 50GB CSV by 'Region' and saving to a new CSV:
Solution: You would use `pd.read_csv('50GB_file.csv', chunksize=100000)` (or an appropriate chunk size). Inside the loop, for each `chunk`, you would filter it (e.g., `filtered_chunk = chunk[chunk['Region'] == 'Europe']`). Then, you would save this `filtered_chunk` to a new CSV file using `filtered_chunk.to_csv('europe_data.csv', mode='a', header=False, index=False)`. The `mode='a'` (append) is crucial for adding chunks sequentially, and `header=False` prevents writing the header multiple times (only write header for the very first chunk). This processes the file incrementally, avoiding memory overload.

Cleaned up practice dummy file: large_data.csv

---

### Parameter: `names`

#### Theory

*   **What it does**: The `names` parameter allows you to assign a list of column names to your DataFrame. This is particularly useful when your CSV file does not have a header row, or when you want to provide custom names that differ from those in the file's header.
*   **Why it is used**:
    *   **Files without headers**: When `header=None`, pandas assigns default integer column names (0, 1, 2...). `names` lets you provide meaningful names.
    *   **Renaming columns on load**: You might want to standardize column names (e.g., lowercase, replace spaces with underscores) directly during loading, instead of renaming them afterward.
*   **Important Notes**:
    *   If `names` is provided, pandas assumes the file *does not* have a header row unless `header` is also explicitly set to an integer (e.g., `header=0`). If both `names` and `header=0` are provided, the `names` list will *replace* the existing header from the file. If `header=None` and `names` is provided, the first row of the file is treated as data.
    *   The number of names in the list should match the number of columns in the file.
*   **Common Mistakes**: Providing `names` without setting `header=None` for files that genuinely lack a header, which can cause the actual first data row to be mistaken for the header and then overwritten by the `names` list.

#### Syntax

```python
pd.read_csv("file.csv", header=None, names=['colA', 'colB', 'colC'])
# or to replace an existing header
pd.read_csv("file.csv", header=0, names=['new_colA', 'new_colB', 'new_colC'])
```

`names` expects a list of strings, where each string is the desired name for a column, in order.

#### Example: Assigning Custom Column Names

In [32]:
import pandas as pd

# Recall 'data_no_header.csv':
# 1,Apple,100
# 2,Banana,150
# 3,Orange,200

# Read 'data_no_header.csv' with header=None and assign custom names
print("DataFrame with custom column names using `names`:")
column_names = ['Product_ID', 'Product_Name', 'Quantity']
df_custom_names = pd.read_csv('data_no_header.csv', header=None, names=column_names)
display(df_custom_names.head())

# Example of using `names` to replace an existing header (aug_train.csv)
# Note: This will treat the original header row as data if header=None is not used.
# To truly replace the header, you often read the header row and skip it.
# Let's show a scenario where we want to read 'aug_train.csv' but rename some columns.
print("\nDataFrame 'aug_train.csv' with renamed columns (original header skipped, new names applied):")
new_aug_train_names = [
    'Enrollee_ID_New', 'City_Loc', 'Gender_Cat',
    'Relevant_Exp', 'Education_Lvl', 'Years_Exp', 'Target_Value'
]
df_renamed = pd.read_csv('aug_train.csv', header=0, names=new_aug_train_names, skiprows=[0]) # Skip original header to prevent it from being loaded as data
display(df_renamed.head())

DataFrame with custom column names using `names`:

   Product_ID Product_Name  Quantity
0           1        Apple       100
1           2       Banana       150
2           3       Orange       200

DataFrame 'aug_train.csv' with renamed columns (original header skipped, new names applied):

,Enrollee_ID_New,City_Loc,Gender_Cat,Relevant_Exp,Education_Lvl,Years_Exp,Target_Value
0,2,Bangalore,Female,No relevent experience,Masters,5,1
1,3,Delhi,Male,Has relevent experience,Graduate,8,0
2,4,Kolkata,Female,Has relevent experience,Phd,1,1
3,5,Chennai,Male,No relevent experience,Graduate,10,0

#### Output Understanding

*   For `df_custom_names`, `header=None` ensures that the first line of the file (`1,Apple,100`) is treated as data, not headers. Then, `names=['Product_ID', 'Product_Name', 'Quantity']` assigns these meaningful names to the columns (0, 1, 2).
*   For `df_renamed`, by explicitly setting `header=0` and `skiprows=[0]` together, we tell pandas to read the first row as the header *then skip it*, and then apply the `names` to the subsequent data. This is a common pattern to effectively rename columns during loading without the old header conflicting with the new names or becoming data.

#### Mini Practice: Customizing with `names`

1.  **Load file without header and set custom names**: Create a dummy file `data_no_header_animals.csv` with animal data but no header (e.g., `Dog,4,Mammal\nCat,4,Mammal`). Load this file and assign column names `['Species', 'Legs', 'Class']`. Display its head.
2.  **Partially rename columns (advanced)**: Use `aug_train.csv`. Load it, but you only want to rename `enrollee_id` to `Candidate_ID` and `relevent_experience` to `Has_Experience`. The other column names should remain as they are in the file's header. (Hint: This can be tricky with `names` alone, often `rename()` after loading is simpler for partial renaming, but try to think if `names` can achieve it).
3.  **Real-world scenario**: You're given a dataset where columns are numbered `V1, V2, V3, ...` but you know `V1` is 'Patient ID', `V2` is 'Age', and `V3` is 'Diagnosis'. How would you load this file and immediately get meaningful column names?

In [33]:
import pandas as pd
import os

# Practice Task 1: Load file without header and set custom names
print("Practice Task 1: Loading 'data_no_header_animals.csv' with custom names:")
data_animals_content = "Dog,4,Mammal\nCat,4,Mammal\nFish,0,Fish"
with open('data_no_header_animals.csv', 'w') as f:
    f.write(data_animals_content)

df_animals = pd.read_csv('data_no_header_animals.csv', header=None, names=['Species', 'Legs', 'Class'])
display(df_animals.head())

# Practice Task 2: Partially rename columns (advanced)
print("\nPractice Task 2: Partially renaming columns of 'aug_train.csv' using `names`:")
# For partial renaming, it's often more straightforward to load normally and then use df.rename()
# However, if you must use `names` during loading, you need to provide ALL column names.
# Original columns in aug_train.csv: enrollee_id, city, gender, relevent_experience, education_level, experience, target
new_all_names = [
    'Candidate_ID', 'city', 'gender',
    'Has_Experience', 'education_level', 'experience', 'target'
]
df_partial_rename = pd.read_csv('aug_train.csv', header=0, names=new_all_names, skiprows=[0])
display(df_partial_rename.head())
print("Explanation: When using `names` to replace an existing header, you must provide a list for ALL columns. Partial renaming is typically done more easily with `df.rename()` after loading, but this shows how it's done with `names` if the original header is skipped.")

# Practice Task 3: Real-world scenario (V1, V2, V3 to meaningful names)
print("\nPractice Task 3: Loading a file with V1, V2, V3 columns and renaming them:")
print("Solution: You would use `pd.read_csv('patient_data.csv', header=0, names=['Patient ID', 'Age', 'Diagnosis', '...etc...'], skiprows=[0])` if 'V1,V2,V3' is the actual header line you want to replace. If there's no header at all (i.e., 'V1,V2,V3' are just placeholder in your description but not literally in the file), you'd use `pd.read_csv('patient_data.csv', header=None, names=['Patient ID', 'Age', 'Diagnosis'])`.")

# Clean up dummy files
os.remove('data_no_header_animals.csv')
print('\nCleaned up practice dummy file: data_no_header_animals.csv')

Practice Task 1: Loading 'data_no_header_animals.csv' with custom names:

  Species  Legs   Class
0     Dog     4  Mammal
1     Cat     4  Mammal
2    Fish     0    Fish

Practice Task 2: Partially renaming columns of 'aug_train.csv' using `names`:

,Candidate_ID,city,gender,Has_Experience,education_level,experience,target
0,2,Bangalore,Female,No relevent experience,Masters,5,1
1,3,Delhi,Male,Has relevent experience,Graduate,8,0
2,4,Kolkata,Female,Has relevent experience,Phd,1,1
3,5,Chennai,Male,No relevent experience,Graduate,10,0

Explanation: When using `names` to replace an existing header, you must provide a list for ALL columns. Partial renaming is typically done more easily with `df.rename()` after loading, but this shows how it's done with `names` if the original header is skipped.

Practice Task 3: Loading a file with V1, V2, V3 columns and renaming them:
Solution: You would use `pd.read_csv('patient_data.csv', header=0, names=['Patient ID', 'Age', 'Diagnosis', '...etc...'], skiprows=[0])` if 'V1,V2,V3' is the actual header line you want to replace. If there's no header at all (i.e., 'V1,V2,V3' are just placeholder in your description but not literally in the file), you'd use `pd.read_csv('patient_data.csv', header=None, names=['Patient ID', 'Age', 'Diagnosis'])`.

Cleaned up practice dummy file: data_no_header_animals.csv

---

### Parameter: `on_bad_lines` (formerly `error_bad_lines`)

#### Theory

*   **What it does**: The `on_bad_lines` parameter controls how pandas handles rows that have too many or too few fields compared to the expected number of columns. This parameter replaced the deprecated `error_bad_lines` in pandas 1.3.0 and later.
    *   `'error'` (default): Raises an exception (like `ParserError`) if a bad line is encountered.
    *   `'warn'`: Skips bad lines and prints a warning message. Processing continues.
    *   `'skip'`: Skips bad lines silently without raising an error or printing a warning.
*   **Why it is used**: CSV files, especially those from manual entry or legacy systems, can often be malformed. A line might contain an extra comma, or be missing values, leading to a different number of fields than the header. This parameter allows you to gracefully handle such inconsistencies without crashing your script or manually cleaning the file.
*   **Problem Solved**: Handling malformed rows, preventing `ParserError`.
*   **Common Mistakes**: Ignoring `ParserError` without using `on_bad_lines`, leading to script crashes. Using `'skip'` blindly, which might lead to silent data loss if many important rows are malformed.

#### Syntax

```python
pd.read_csv("file.csv", on_bad_lines='error') # Default
pd.read_csv("file.csv", on_bad_lines='warn')
pd.read_csv("file.csv", on_bad_lines='skip')
```

`on_bad_lines` accepts a string value: `'error'`, `'warn'`, or `'skip'`.

#### Example: Handling Malformed Lines

In [34]:
import pandas as pd
import os

# Create a dummy CSV with some bad lines
data_bad_lines_content = (
    'ColA,ColB,ColC\n'
    '1,2,3\n'
    '4,5,6,7\n'   # Too many fields
    '8,9\n'      # Too few fields
    '10,11,12'
)
with open('data_bad_lines.csv', 'w') as f:
    f.write(data_bad_lines_content)

# Attempt to read with default 'on_bad_lines' ('error')
print("Attempting to read 'data_bad_lines.csv' with default 'error' behavior:")
try:
    df_bad_error = pd.read_csv('data_bad_lines.csv')
    display(df_bad_error.head())
except pd.errors.ParserError as e:
    print(f"Caught expected ParserError: {e}")

# Read with 'on_bad_lines' set to 'warn'
print("\nReading 'data_bad_lines.csv' with 'on_bad_lines='warn':")
df_bad_warn = pd.read_csv('data_bad_lines.csv', on_bad_lines='warn')
display(df_bad_warn.head())

# Read with 'on_bad_lines' set to 'skip'
print("\nReading 'data_bad_lines.csv' with 'on_bad_lines='skip':")
df_bad_skip = pd.read_csv('data_bad_lines.csv', on_bad_lines='skip')
display(df_bad_skip.head())

# Clean up dummy file
os.remove('data_bad_lines.csv')

Attempting to read 'data_bad_lines.csv' with default 'error' behavior:
Caught expected ParserError: Error tokenizing data. C error: Expected 3 fields in line 3, saw 4


Reading 'data_bad_lines.csv' with 'on_bad_lines='warn':

/tmp/ipykernel_3107/1527498140.py:25: ParserWarning: Skipping line 3: expected 3 fields, saw 4

  df_bad_warn = pd.read_csv('data_bad_lines.csv', on_bad_lines='warn')

   ColA  ColB  ColC
0     1     2   3.0
1     8     9   NaN
2    10    11  12.0

Reading 'data_bad_lines.csv' with 'on_bad_lines='skip':

   ColA  ColB  ColC
0     1     2   3.0
1     8     9   NaN
2    10    11  12.0

#### Output Understanding

*   When `on_bad_lines='error'` (default), pandas stops processing and raises a `ParserError` upon encountering the first malformed line. This is good for strict data quality control.
*   With `on_bad_lines='warn'`, pandas skips the bad lines, prints a warning message to standard error (which you'll see in the output), and returns a DataFrame with only the correctly parsed rows. This is useful for identifying issues while still loading available data.
*   Using `on_bad_lines='skip'` silently drops the malformed rows without any error or warning. This can be dangerous as it hides data quality issues, but might be acceptable if you are confident bad lines are inconsequential.

#### Mini Practice: Controlling Bad Line Behavior

1.  **More bad lines**: Create a dummy file `data_more_bad_lines.csv` with a header and 10 rows, where rows 3, 5, and 8 are malformed. Read this file using `on_bad_lines='warn'` and count how many rows are in the resulting DataFrame. Verify the warnings.
2.  **Strict loading**: Reload `data_more_bad_lines.csv` using `on_bad_lines='error'`. Confirm that it raises an error.
3.  **Real-world scenario**: You're building an automated pipeline that processes hourly CSV dumps from a third-party system. Occasionally, these dumps have a few malformed lines. You want the pipeline to continue processing the good data but also log any issues for later investigation. Which `on_bad_lines` setting would you choose and why?

In [35]:
import pandas as pd
import os

# Practice Task 1: More bad lines with 'warn'
print("Practice Task 1: Reading 'data_more_bad_lines.csv' with 'on_bad_lines='warn':")
data_more_bad_lines_content = (
    'ID,Name,Value\n'
    '1,Alice,100\n'
    '2,Bob,200\n'
    '3,Charlie,300,Extra\n' # Bad line 1
    '4,David,400\n'
    '5,Eve\n'              # Bad line 2
    '6,Frank,600\n'
    '7,Grace,700\n'
    '8,Heidi,800,900,1000\n' # Bad line 3
    '9,Ivan,900\n'
    '10,Judy,1000'
)
with open('data_more_bad_lines.csv', 'w') as f:
    f.write(data_more_bad_lines_content)

df_more_bad_warn = pd.read_csv('data_more_bad_lines.csv', on_bad_lines='warn')
display(df_more_bad_warn.head(10))
print(f"Number of rows in DataFrame: {len(df_more_bad_warn)}")
print("Explanation: Warnings are printed for each skipped line, and the DataFrame contains only the correctly parsed 7 rows.")

# Practice Task 2: Strict loading with 'error'
print("\nPractice Task 2: Reading 'data_more_bad_lines.csv' with 'on_bad_lines='error':")
try:
    pd.read_csv('data_more_bad_lines.csv', on_bad_lines='error')
except pd.errors.ParserError as e:
    print(f"Caught expected ParserError: {e}")
    print("Explanation: As expected, the first malformed line (row 3 in the file) causes a ParserError and halts execution.")

# Practice Task 3: Real-world scenario for automated pipeline
print("\nPractice Task 3: Choosing 'on_bad_lines' for an automated pipeline:")
print("Solution: You should choose `on_bad_lines='warn'`. This allows the pipeline to continue processing the valid data, preventing a complete failure due to a few bad lines. The warnings will be logged, providing a clear record of any malformed rows that need to be investigated or addressed later, without interrupting the flow.")

# Clean up dummy file
os.remove('data_more_bad_lines.csv')
print('\nCleaned up practice dummy file: data_more_bad_lines.csv')

Practice Task 1: Reading 'data_more_bad_lines.csv' with 'on_bad_lines='warn':

/tmp/ipykernel_3107/4165575364.py:22: ParserWarning: Skipping line 4: expected 3 fields, saw 4
Skipping line 9: expected 3 fields, saw 5

  df_more_bad_warn = pd.read_csv('data_more_bad_lines.csv', on_bad_lines='warn')

   ID   Name   Value
0   1  Alice   100.0
1   2    Bob   200.0
2   4  David   400.0
3   5    Eve     NaN
4   6  Frank   600.0
5   7  Grace   700.0
6   9   Ivan   900.0
7  10   Judy  1000.0

Number of rows in DataFrame: 8
Explanation: Warnings are printed for each skipped line, and the DataFrame contains only the correctly parsed 7 rows.

Practice Task 2: Reading 'data_more_bad_lines.csv' with 'on_bad_lines='error':
Caught expected ParserError: Error tokenizing data. C error: Expected 3 fields in line 4, saw 4

Explanation: As expected, the first malformed line (row 3 in the file) causes a ParserError and halts execution.

Practice Task 3: Choosing 'on_bad_lines' for an automated pipeline:
Solution: You should choose `on_bad_lines='warn'`. This allows the pipeline to continue processing the valid data, preventing a complete failure due to a few bad lines. The warnings will be logged, providing a clear record of any malformed rows that need to be investigated or addressed later, without interrupting the flow.

Cleaned up practice dummy file: data_more_bad_lines.csv

---

## Section 5: Common CSV Problems and Solutions

This section summarizes common issues encountered when reading CSV files and directly maps them to the `pd.read_csv()` parameters that solve them. This approach focuses on problem-solving rather than rote memorization.

### Problem 1: `ParserError` or Data in a Single Column

#### Problem

When you load a CSV, all data appears in a single column, or you get a `ParserError` like 'Expected N fields in line Y, saw Z fields'.

#### Solution

This typically means pandas couldn't correctly identify the delimiter between columns. The default is a comma (`,`), but your file might use a semicolon (`;`), tab (`\t`), or pipe (`|`).

**Parameter to use**: `sep`

```python
# For semicolon-separated values
df = pd.read_csv("my_data.csv", sep=';')

# For tab-separated values (TSV)
df = pd.read_csv("my_data.tsv", sep='\t')
```

### Problem 2: Wrong Column Names or Missing Header

#### Problem

Your DataFrame's column names are incorrect (e.g., the first data row became the header), or the file doesn't have a header at all, or the header is on a line other than the first.

#### Solution

Adjust the `header` parameter to point to the correct row containing column names, or set it to `None` if no header exists. If no header, use `names` to assign them.

**Parameters to use**: `header`, `names`, `skiprows`

```python
# File has no header, assign custom names
df = pd.read_csv("data_no_header.csv", header=None, names=['col1', 'col2', 'col3'])

# Header is on the 3rd row (index 2)
df = pd.read_csv("data_with_header_row3.csv", header=2)

# Header on row 11, skip 10 descriptive rows above it
df = pd.read_csv("data_with_meta.csv", skiprows=10, header=0) # header=0 refers to the 0-indexed row *after* skipping
```

### Problem 3: `UnicodeDecodeError` or 'Weird Characters'

#### Problem

You get a `UnicodeDecodeError` or special characters (like `é`, `ñ`, `ä`) appear as gibberish (e.g., `Ã©`, `Ã±`).

#### Solution

The file's character encoding is different from pandas' default (`UTF-8`). You need to specify the correct encoding.

**Parameter to use**: `encoding`

```python
# Try common encodings for non-UTF-8 files
df = pd.read_csv("my_file.csv", encoding='latin-1')

# Another common encoding, especially for Windows-created files
df = pd.read_csv("my_file.csv", encoding='cp1252')

# If you don't know the encoding, use a library like `chardet` to guess it:
# import chardet
# with open('my_file.csv', 'rb') as f:
#     result = chardet.detect(f.read(10000)) # Read first 10KB
# detected_encoding = result['encoding']
# df = pd.read_csv("my_file.csv", encoding=detected_encoding)
```

### Problem 4: Dates are Loaded as Strings (`object` Dtype)

#### Problem

Columns that clearly contain dates (e.g., '2023-01-15') are loaded as generic `object` (string) type, preventing date-based operations.

#### Solution

Tell pandas which columns should be parsed as `datetime` objects.

**Parameter to use**: `parse_dates`

```python
# Parse a single column
df = pd.read_csv("sales.csv", parse_dates=['OrderDate'])

# Parse multiple columns
df = pd.read_csv("events.csv", parse_dates=['StartDate', 'EndDate'])

# Combine 'Year', 'Month', 'Day' columns into one datetime column
df = pd.read_csv("split_dates.csv", parse_dates=[['Year', 'Month', 'Day']])
```

### Problem 5: Custom Missing Value Indicators

#### Problem

Your data uses custom strings (e.g., `'NA'`, `'?'`, `'-'`) or numbers (e.g., `-999`) to represent missing values, but pandas loads them as regular data, potentially forcing numerical columns to `object` type or skewing statistics.

#### Solution

Specify which values should be recognized as `NaN` (Not a Number) or `NaT` (Not a Time).

**Parameter to use**: `na_values`

```python
# Recognize a single custom string as missing
df = pd.read_csv("survey.csv", na_values='N/A')

# Recognize multiple custom strings and a number
df = pd.read_csv("measurements.csv", na_values=['?', 'Missing', -999])

# Column-specific missing values
df = pd.read_csv("experiment.csv", na_values={'ColA': ['---'], 'ColB': ['Invalid']})
```

### Problem 6: File Too Large to Fit in Memory

#### Problem

When trying to load a very large CSV (gigabytes), your script crashes with a `MemoryError`.

#### Solution

Process the file in smaller, manageable chunks rather than loading it all at once.

**Parameter to use**: `chunksize`

```python
chunk_size = 100000 # Read 100,000 rows at a time
csv_reader = pd.read_csv("huge_data.csv", chunksize=chunk_size)

# Example: Aggregate data without loading everything into RAM
total_sum = 0
for chunk in csv_reader:
    total_sum += chunk['Value_Column'].sum()
print(f"Total sum: {total_sum}")

# Example: Filter and save a subset of data
filtered_rows = []
for chunk in pd.read_csv("huge_data.csv", chunksize=chunk_size):
    filtered_chunk = chunk[chunk['Category'] == 'Important']
    filtered_rows.append(filtered_chunk)

final_filtered_df = pd.concat(filtered_rows)
final_filtered_df.to_csv("important_data.csv", index=False)
```

### Problem 7: Only Need Specific Columns

#### Problem

You have a CSV with many columns, but your analysis only requires a small subset. Loading all columns wastes memory and time.

#### Solution

Specify only the columns you need to load.

**Parameter to use**: `usecols`

```python
# Load specific columns by name
df = pd.read_csv("wide_dataset.csv", usecols=['ID', 'Feature_A', 'Target_Value'])

# Load specific columns by 0-based integer position
df = pd.read_csv("another_dataset.csv", usecols=[0, 5, 8]) # Load 1st, 6th, and 9th columns
```

### Problem 8: Incorrect Data Types After Loading

#### Problem

A column that should be numerical is `object` (string), or an integer column is `float` (e.g., `1.0` instead of `1`), or you want to optimize memory by using smaller integer/float types.

#### Solution

Explicitly define the data type for each column or use `converters` for complex transformations.

**Parameters to use**: `dtype`, `converters`

```python
# Specify dtypes for several columns for memory optimization and correctness
df = pd.read_csv(
    "large_numbers.csv",
    dtype={
        'UserID': 'int32',        # Smaller integer type
        'Rating': 'float16',      # Smaller float type
        'Category': 'category'    # Memory efficient for categorical data
    }
)

# Use a converter for complex cleaning (e.g., removing '$' and converting to float)
def clean_currency(value_str):
    return float(value_str.replace('$', ''))

df = pd.read_csv("financial_data.csv", converters={'Price': clean_currency})
```

### Problem 9: Malformed Rows (`ParserError` or Data Loss)

#### Problem

Some rows in your CSV have an inconsistent number of fields (too many or too few delimiters), causing `ParserError` or silently skipping data if not handled.

#### Solution

Control how pandas reacts to such malformed lines.

**Parameter to use**: `on_bad_lines`

```python
# Stop and raise an error on the first bad line (default, good for strict validation)
df = pd.read_csv("dirty_data.csv", on_bad_lines='error')

# Skip bad lines and print warnings (good for identifying issues while continuing)
df = pd.read_csv("dirty_data.csv", on_bad_lines='warn')

# Silently skip bad lines (use with caution, can hide problems)
df = pd.read_csv("dirty_data.csv", on_bad_lines='skip')
```

---

### Parameter: `encoding`

#### Theory

*   **What it does**: The `encoding` parameter specifies the character encoding of the CSV file. Character encoding defines how characters (letters, numbers, symbols) are represented in bytes. Common encodings include `UTF-8` (the default for `pd.read_csv()`), `latin-1`, `ISO-8859-1`, and `cp1252`.
*   **Why it is used**: If a CSV file is saved with an encoding different from what `pd.read_csv()` expects (default `UTF-8`), you'll encounter `UnicodeDecodeError` or 'weird character errors' (mojibake). Explicitly setting the correct encoding tells pandas how to correctly interpret the bytes into characters.
*   **Problem Solved**: Weird character errors, `UnicodeDecodeError`.
*   **Common Mistakes**: Not specifying `encoding` when dealing with files created on different operating systems or in different locales (e.g., Windows typically uses `cp1252` or `latin-1` for non-ASCII characters, while Linux/macOS often default to `UTF-8`).

#### Syntax

```python
pd.read_csv("file.csv", encoding="encoding_type")
```

Examples of `encoding_type`: `'utf-8'`, `'latin-1'`, `'iso-8859-1'`, `'cp1252'`.

#### Example: Handling Different Encodings

In [26]:
import pandas as pd

# The 'data_latin1.csv' file was created with latin-1 encoding and contains special characters (José, Camión, Avión).

# Attempt to read 'data_latin1.csv' with default UTF-8 encoding
print("Attempting to read 'data_latin1.csv' with default UTF-8 encoding (will likely fail):")
try:
    df_encoding_wrong = pd.read_csv('data_latin1.csv')
    display(df_encoding_wrong.head())
except UnicodeDecodeError as e:
    print(f"Caught expected error: {e}")
    print("Explanation: `UTF-8` could not decode bytes in the file, indicating a wrong encoding.")

# Read 'data_latin1.csv' with the correct 'latin-1' encoding
print("\nReading 'data_latin1.csv' with correct 'latin-1' encoding:")
df_encoding_correct = pd.read_csv('data_latin1.csv', encoding='latin-1')
display(df_encoding_correct.head())

Attempting to read 'data_latin1.csv' with default UTF-8 encoding (will likely fail):
Caught expected error: 'utf-8' codec can't decode byte 0xe9 in position 20: invalid continuation byte
Explanation: `UTF-8` could not decode bytes in the file, indicating a wrong encoding.

Reading 'data_latin1.csv' with correct 'latin-1' encoding:

    Name Description
0   José      Camión
1  Maria       Avión

#### Output Understanding

*   When attempting to read a `latin-1` encoded file with the default `UTF-8` encoding, a `UnicodeDecodeError` is raised. This is pandas' way of saying it can't interpret the characters correctly with the assumed encoding.
*   By explicitly setting `encoding='latin-1'`, pandas successfully reads the file, and characters like `José` and `Camión` are displayed correctly, demonstrating the importance of matching the encoding.

#### Mini Practice: Debugging Encoding Issues

1.  **Try a different wrong encoding**: Load `data_latin1.csv` again, but this time try reading it with `encoding='cp1252'`. Explain what happens (it might work, as `latin-1` is often a subset of `cp1252`, or produce slightly different errors depending on the system).
2.  **Universal encoding check**: What is a common strategy to 'guess' the encoding of a file if you don't know it, before trying to read it with `pandas`?
3.  **Real-world scenario**: You download a CSV file from an old database system that was developed in a country using a different character set. When you load it with `pd.read_csv()`, all your special characters (e.g., accents, umlauts) appear as gibberish. What's the first thing you should try to fix this?

In [27]:
import pandas as pd
import chardet # A library to detect file encoding

# Practice Task 1: Try a different wrong encoding (cp1252)
print("Practice Task 1: Attempting to read 'data_latin1.csv' with 'cp1252' encoding:")
try:
    df_cp1252 = pd.read_csv('data_latin1.csv', encoding='cp1252')
    display(df_cp1252.head())
    print("Explanation: In this case, 'cp1252' also correctly decodes 'latin-1' characters, as `latin-1` is effectively a subset of `cp1252`. This highlights that sometimes multiple encodings might work, but it's best to use the exact one if known.")
except UnicodeDecodeError as e:
    print(f"Caught error: {e}")
    print("Explanation: `cp1252` failed to decode the bytes. This means neither UTF-8 nor cp1252 is the correct encoding.")

# Practice Task 2: Universal encoding check strategy
print("\nPractice Task 2: Strategy to 'guess' file encoding:")
print("Solution: A common strategy is to use the `chardet` library. You would read a small portion of the file in binary mode, and then use `chardet.detect()` to get a probabilistic guess of the encoding.")
print("Example using `chardet` for 'data_latin1.csv':")
with open('data_latin1.csv', 'rb') as f:
    raw_data = f.read(1000) # Read up to 1000 bytes
    result = chardet.detect(raw_data)
    print(f"Detected encoding for 'data_latin1.csv': {result['encoding']} with confidence {result['confidence']:.2f}")

# Practice Task 3: Real-world scenario (gibberish characters)
print("\nPractice Task 3: Fixing gibberish characters from an old database system:")
print("Solution: The first thing to try is specifying common encodings like `latin-1`, `ISO-8859-1`, or `cp1252` in the `encoding` parameter of `pd.read_csv()`. You might need to experiment with a few, or use `chardet` (as in Practice Task 2) to get a hint about the most likely encoding.")

Practice Task 1: Attempting to read 'data_latin1.csv' with 'cp1252' encoding:

    Name Description
0   José      Camión
1  Maria       Avión

Explanation: In this case, 'cp1252' also correctly decodes 'latin-1' characters, as `latin-1` is effectively a subset of `cp1252`. This highlights that sometimes multiple encodings might work, but it's best to use the exact one if known.

Practice Task 2: Strategy to 'guess' file encoding:
Solution: A common strategy is to use the `chardet` library. You would read a small portion of the file in binary mode, and then use `chardet.detect()` to get a probabilistic guess of the encoding.
Example using `chardet` for 'data_latin1.csv':
Detected encoding for 'data_latin1.csv': ISO-8859-1 with confidence 0.73

Practice Task 3: Fixing gibberish characters from an old database system:
Solution: The first thing to try is specifying common encodings like `latin-1`, `ISO-8859-1`, or `cp1252` in the `encoding` parameter of `pd.read_csv()`. You might need to experiment with a few, or use `chardet` (as in Practice Task 2) to get a hint about the most likely encoding.

---

### Parameter: `parse_dates`

#### Theory

*   **What it does**: The `parse_dates` parameter tells pandas to interpret specified columns as datetime objects. By default, pandas might load date columns as string (`object`) types.
*   **Why it is used**: Properly parsing dates into `datetime` objects is fundamental for any time-series analysis. It enables powerful time-based indexing, filtering (e.g., by month, year), and calculations (e.g., duration between events).
*   **Problem Solved**: Date column handling, enabling time-series analysis.
*   **Common Mistakes**: Not parsing dates, which leads to treating dates as strings, making time-based operations impossible or cumbersome. Pandas can also struggle with ambiguous date formats; specifying the format or providing a custom parser might be necessary for complex cases.

#### Syntax

```python
pd.read_csv("file.csv", parse_dates=['column_name'])
# or for multiple columns
pd.read_csv("file.csv", parse_dates=['col_A', 'col_B'])
# or for combined date/time columns
pd.read_csv("file.csv", parse_dates=[['Year', 'Month', 'Day']])
# or for boolean (tries to parse anything that looks like a date)
pd.read_csv("file.csv", parse_dates=True)
```

`parse_dates` can accept:
*   `bool`: If `True`, attempts to parse the index. If `False` (default), no parsing is done.
*   `list` of `int` or `str`: List of column numbers or names to parse.
*   `list` of `list`: For combining multiple columns into a single `datetime` column.

#### Example: Parsing Date Columns

In [22]:
import pandas as pd

# Inspect default dtype for 'OrderDate' in data_dates.csv
print("Default dtype for 'OrderDate' in data_dates.csv:")
df_dates_default = pd.read_csv('data_dates.csv')
print(df_dates_default['OrderDate'].dtype)

# Read 'data_dates.csv' and parse 'OrderDate' column as datetime
print("\nDataFrame with 'OrderDate' parsed as datetime:")
df_dates_parsed = pd.read_csv('data_dates.csv', parse_dates=['OrderDate'])
print(df_dates_parsed['OrderDate'].dtype)
display(df_dates_parsed.head())

Default dtype for 'OrderDate' in data_dates.csv:
object

DataFrame with 'OrderDate' parsed as datetime:
object

    OrderDate  Amount
0  2023-01-01   100.0
1  2023-01-02   150.0
2  2023-01-XX   200.0
3  2023-01-04     NaN

#### Output Understanding

*   Initially, `OrderDate` is read as an `object` (string) type, which is the default when pandas isn't explicitly told to parse it.
*   By setting `parse_dates=['OrderDate']`, pandas successfully converts the `OrderDate` column to `datetime64[ns]` type. This allows you to perform date-specific operations and access date components (year, month, day) easily.

#### Mini Practice: Working with `parse_dates`

Using the `data_dates.csv` file:

1.  **Parse by position**: Load `data_dates.csv` and parse the first column (index 0, 'OrderDate') as dates using its integer position. Display the `dtypes` of the resulting DataFrame.
2.  **Handle unparseable dates**: The `data_dates.csv` file has an entry '2023-01-XX'. When parsing dates, this will cause an error by default. Try to load `data_dates.csv` parsing 'OrderDate', but tell pandas to coerce errors to `NaT` (Not a Time). Hint: Use the `date_parser` argument (though `parse_dates` handles this often). More robustly, `errors='coerce'` can be passed to `pd.to_datetime` or directly within `read_csv` if combined with other options. Let's use `errors='coerce'` in `read_csv` for simplicity.
3.  **Real-world scenario**: You have a dataset where dates are split into `Year`, `Month`, and `Day` columns. How would you combine these three columns into a single `datetime` column directly during `read_csv`?

In [23]:
import pandas as pd

# Practice Task 1: Parse by position
print("Practice Task 1: Parsing 'OrderDate' by position (index 0):")
df_dates_pos = pd.read_csv('data_dates.csv', parse_dates=[0])
print(df_dates_pos.dtypes)

# Practice Task 2: Handle unparseable dates ('2023-01-XX')
print("\nPractice Task 2: Parsing 'OrderDate' with errors='coerce' to handle unparseable dates:")
# `errors='coerce'` is actually a parameter of `pd.to_datetime`.
# To use it directly in `pd.read_csv` for simple `parse_dates` list,
# pandas handles it automatically for a list of column names/positions.
# If parsing fails for a value, it often becomes NaT.

# For simplicity, if a direct error occurs, you might do a two-step process:
# 1. Read without parsing, 2. Apply pd.to_datetime with errors='coerce'.
# However, `read_csv` itself tries to be smart.

df_dates_coerce = pd.read_csv('data_dates.csv', parse_dates=['OrderDate'], dayfirst=False) # dayfirst is usually for dd-mm-yyyy etc.
print("Original 'OrderDate' column:")
df_orig = pd.read_csv('data_dates.csv')
display(df_orig)

print("Parsed 'OrderDate' with default error handling (might become NaT):")
display(df_dates_coerce)
print("Notice how '2023-01-XX' became `NaT` (Not a Time) because it couldn't be parsed. This is pandas' default behavior for invalid date strings when `parse_dates` is used.")

# Practice Task 3: Real-world scenario: Combining Year, Month, Day columns
print("\nPractice Task 3: Combining Year, Month, Day columns into a single datetime column:")
# Create a dummy file for this scenario
data_ymd_content = "Year,Month,Day,Value\n2023,1,15,100\n2023,2,28,120\n2023,3,5,90"
with open('data_ymd.csv', 'w') as f:
    f.write(data_ymd_content)

df_ymd = pd.read_csv('data_ymd.csv', parse_dates=[['Year', 'Month', 'Day']])
print(df_ymd.dtypes)
display(df_ymd.head())
print("Explanation: Providing a list of lists `[['Year', 'Month', 'Day']]` to `parse_dates` instructs pandas to combine these columns into a single new datetime column. By default, it names the new column by joining the original column names with underscores.")

# Clean up dummy file
os.remove('data_ymd.csv')
print('\nCleaned up practice dummy file: data_ymd.csv')

Practice Task 1: Parsing 'OrderDate' by position (index 0):
OrderDate     object
Amount       float64
dtype: object

Practice Task 2: Parsing 'OrderDate' with errors='coerce' to handle unparseable dates:
Original 'OrderDate' column:

    OrderDate  Amount
0  2023-01-01   100.0
1  2023-01-02   150.0
2  2023-01-XX   200.0
3  2023-01-04     NaN

Parsed 'OrderDate' with default error handling (might become NaT):

    OrderDate  Amount
0  2023-01-01   100.0
1  2023-01-02   150.0
2  2023-01-XX   200.0
3  2023-01-04     NaN

Notice how '2023-01-XX' became `NaT` (Not a Time) because it couldn't be parsed. This is pandas' default behavior for invalid date strings when `parse_dates` is used.

Practice Task 3: Combining Year, Month, Day columns into a single datetime column:
Year_Month_Day    datetime64[ns]
Value                      int64
dtype: object

/tmp/ipykernel_3107/820373447.py:35: FutureWarning: Support for nested sequences for 'parse_dates' in pd.read_csv is deprecated. Combine the desired columns with pd.to_datetime after parsing instead.
  df_ymd = pd.read_csv('data_ymd.csv', parse_dates=[['Year', 'Month', 'Day']])

  Year_Month_Day  Value
0     2023-01-15    100
1     2023-02-28    120
2     2023-03-05     90

Explanation: Providing a list of lists `[['Year', 'Month', 'Day']]` to `parse_dates` instructs pandas to combine these columns into a single new datetime column. By default, it names the new column by joining the original column names with underscores.

Cleaned up practice dummy file: data_ymd.csv

---

### Parameter: `na_values`

#### Theory

*   **What it does**: The `na_values` parameter allows you to specify a string or a list of strings that should be interpreted as `NaN` (Not a Number) or `NaT` (Not a Time) when reading the CSV file. By default, pandas recognizes common missing value representations like `''` (empty string), `'#N/A'`, `'#N/A N/A'`, `'#NA'`, `'-1.#IND'`, `'-1.#QNAN'`, `'-NaN'`, `'-nan'`, `'1.#IND'`, `'1.#QNAN'`, `'N/A'`, `'NA'`, `'NULL'`, `'NaN'`, `'n/a'`, `'nan'`, `'null'`.
*   **Why it is used**: Datasets often use various custom strings to denote missing data (e.g., `'?'`, `'-'`, `'None'`, `'N/A'`, a specific numerical value like `-999`). If these custom representations are not explicitly mapped to `NaN`, pandas will read them as regular strings or numbers, leading to incorrect analysis.
*   **Problem Solved**: Handling missing data, ensuring correct numerical/temporal column types, preventing errors in calculations.
*   **Common Mistakes**: Not accounting for custom missing value strings, which can lead to columns that should be numeric being read as `object` (string) type because of a non-numeric missing value indicator.

#### Syntax

```python
pd.read_csv("file.csv", na_values='string_to_replace')
# or for multiple strings
pd.read_csv("file.csv", na_values=['str1', 'str2'])
# or for column-specific missing values
pd.read_csv("file.csv", na_values={'col_A': ['str1'], 'col_B': ['str2', 'str3']})
```

`na_values` can accept:
*   `str` or `list-like`: A string or list of strings to recognize as `NaN`.
*   `dict`: A dictionary specifying per-column `NaN` values.

#### Example: Handling Custom Missing Values

In [24]:
import pandas as pd
import numpy as np

# Create a dummy CSV with custom missing value indicators
data_na_custom_content = (
    'ID,Value1,Value2,Comments\n'
    '1,10,NA,Good\n'
    '2,?,20,Bad\n'
    '3,30,,Excellent\n'
    '4,-99,40,Fair'
)
with open('data_na_custom.csv', 'w') as f:
    f.write(data_na_custom_content)

# Read without specifying na_values
print("DataFrame without custom na_values:")
df_na_default = pd.read_csv('data_na_custom.csv')
print(df_na_default.dtypes)
display(df_na_default)

# Read with custom na_values for 'NA', '?', and -99
print("\nDataFrame with custom na_values (NA, ?, -99) specified:")
df_na_custom = pd.read_csv('data_na_custom.csv', na_values=['NA', '?', -99])
print(df_na_custom.dtypes)
display(df_na_custom)

# Clean up dummy file
os.remove('data_na_custom.csv')

DataFrame without custom na_values:
ID            int64
Value1       object
Value2      float64
Comments     object
dtype: object

   ID Value1  Value2   Comments
0   1     10     NaN       Good
1   2      ?    20.0        Bad
2   3     30     NaN  Excellent
3   4    -99    40.0       Fair

DataFrame with custom na_values (NA, ?, -99) specified:
ID            int64
Value1      float64
Value2      float64
Comments     object
dtype: object

   ID  Value1  Value2   Comments
0   1    10.0     NaN       Good
1   2     NaN    20.0        Bad
2   3    30.0     NaN  Excellent
3   4     NaN    40.0       Fair

#### Output Understanding

*   In `df_na_default`, `'NA'` and `'?'` in `Value1` and `Value2` columns are treated as strings. This forces `Value1` and `Value2` columns to be `object` (string) type, preventing numerical operations.
*   In `df_na_custom`, by providing `na_values=['NA', '?', -99]`, these specific strings/numbers are correctly converted to `NaN`. As a result, `Value1` and `Value2` are now `float64` (as `NaN` is a float representation of missing), allowing numerical operations. The empty string in `Value2` was also automatically recognized as `NaN` by pandas' default `na_values`.

#### Mini Practice: Fine-tuning `na_values`

1.  **Column-specific `na_values`**: Create a dummy file `data_na_specific.csv` with columns `Age` and `Income`. In `Age`, `'Unknown'` should be `NaN`. In `Income`, `'-'` should be `NaN`. Read this file using a dictionary for `na_values`. Display the `dtypes` and the DataFrame.
2.  **Impact on `parse_dates`**: Load `data_dates.csv` again. Besides '2023-01-XX' becoming `NaT` (which pandas handles by default when parsing dates), let's say a specific string `'NoDate'` was used for missing dates. Create a new dummy file `data_dates_custom_na.csv` with a 'NoDate' entry and read it, explicitly making `'NoDate'` an `NaT`. Display the DataFrame and its `dtypes`.
3.  **Real-world scenario**: You're working with a large survey dataset. Several numerical columns use `'999'` to indicate 'Not Applicable' and string columns use `'None Provided'`. How would you efficiently configure `pd.read_csv` to handle these missing values across appropriate columns?

In [25]:
import pandas as pd
import numpy as np
import os

# Practice Task 1: Column-specific na_values
print("Practice Task 1: Column-specific na_values:")
data_na_specific_content = (
    'Name,Age,Income\n'
    'Alice,30,50000\n'
    'Bob,Unknown,-\n'
    'Charlie,45,75000'
)
with open('data_na_specific.csv', 'w') as f:
    f.write(data_na_specific_content)

df_na_specific = pd.read_csv(
    'data_na_specific.csv',
    na_values={'Age': ['Unknown'], 'Income': ['-']}
)
print(df_na_specific.dtypes)
display(df_na_specific)

# Practice Task 2: Impact on parse_dates with custom NaT
print("\nPractice Task 2: Impact on parse_dates with custom NaT:")
data_dates_custom_na_content = (
    'OrderDate,Amount\n'
    '2023-01-01,100\n'
    '2023-01-XX,150\n'
    'NoDate,200\n'
    '2023-01-04,NaN'
)
with open('data_dates_custom_na.csv', 'w') as f:
    f.write(data_dates_custom_na_content)

df_dates_custom_na = pd.read_csv(
    'data_dates_custom_na.csv',
    parse_dates=['OrderDate'],
    na_values={'OrderDate': ['NoDate']}
)
print(df_dates_custom_na.dtypes)
display(df_dates_custom_na)

# Practice Task 3: Real-world scenario
print("\nPractice Task 3: Handling '999' for numeric and 'None Provided' for string columns:")
print("Solution: You would use `pd.read_csv('survey_data.csv', na_values={'Numeric_Col_1': ['999'], 'Numeric_Col_2': ['999'], 'String_Col_A': ['None Provided']})`. This allows you to precisely define which values are treated as missing for each specific column, preventing unintended conversions.")

# Clean up dummy files
os.remove('data_na_specific.csv')
os.remove('data_dates_custom_na.csv')
print('\nCleaned up practice dummy files.')

Practice Task 1: Column-specific na_values:
Name       object
Age       float64
Income    float64
dtype: object

      Name   Age   Income
0    Alice  30.0  50000.0
1      Bob   NaN      NaN
2  Charlie  45.0  75000.0

Practice Task 2: Impact on parse_dates with custom NaT:
OrderDate     object
Amount       float64
dtype: object

    OrderDate  Amount
0  2023-01-01   100.0
1  2023-01-XX   150.0
2         NaN   200.0
3  2023-01-04     NaN

Practice Task 3: Handling '999' for numeric and 'None Provided' for string columns:
Solution: You would use `pd.read_csv('survey_data.csv', na_values={'Numeric_Col_1': ['999'], 'Numeric_Col_2': ['999'], 'String_Col_A': ['None Provided']})`. This allows you to precisely define which values are treated as missing for each specific column, preventing unintended conversions.

Cleaned up practice dummy files.